### PR TITLE
Prefix all Ginkgo macros 

### LINKED ISSUE #184: Prefixing public macros with GKO or similar
After #183, `core/base/exception_helpers.hpp` is going to be a public header, which means the global namespace is polluted with the macros defined in there (e.g. `NOT_SUPPORTED`, `NOT_IMPLEMENTED`, `ASSERT_[...]` and `ENSURE_[...]`).

We should at least prefix them at some point with `GKO_` (as we do with Factories) or `GKO_DETAIL_` and find out what other macros in the public header need to be prefixed.

### PR DESCRIPTION
**Pull request by tcojean**
Prefix all Ginkgo macros and unify their usages for better compatibility with other projects. Closes #184.

This is also required for xSDK compatibility (statement M9 [[1]]). This MR gives us full compatibility with M9. This is also a nice thing to have before the first release.
```
M9. Use a limited and well-defined symbol, macro, library, and include file name space.
```

[1]: https://github.com/ginkgo-project/xsdk-policy-compatibility/blob/master/ginkgo-policy-compatibility.md

### Description
+ Every macro, public or private, gets a `GKO_` prefix.
+ There are multiple reasons for prefixing private macros, among which:
  + Do not overwrite public macros by mistake,
  + Identify Ginkgo macros from external ones,
  + This is simpler for coding: always use a `GKO_` prefix, period.
+ All `#undef` are removed from `.cpp` files as these macros do not impact other
  files. The only exception is the module related macro `GKO_HOOK_MODULE`.
+ Some file guards did not use a `GKO_` prefix, this is now also fixed.

### Before merging
+ [x] Merge #235,
+ [x] Merge #197,
+ [x] Merge #198,
+ [x] Rebase this MR and update it.

### After merging
+ [x] Update [our xSDK compatibility list](https://github.com/ginkgo-project/xsdk-policy-compatibility/),
+ [x] Update our coding style wiki page to mention always prefixing macros with `GKO_`.

### CODE REVIEW

File: core/test/base/exception_helpers.cpp [hunk 1]
```diff
@@ -40,47 +40,47 @@ SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 namespace {
 
 
-void not_implemented_func() NOT_IMPLEMENTED;
+void not_implemented_func() GKO_NOT_IMPLEMENTED;
 
 TEST(NotImplemented, ThrowsWhenUsed)
 {
     ASSERT_THROW(not_implemented_func(), gko::NotImplemented);
```
Comment (hartwiganzt) [inline core/test/base/exception_helpers.cpp]: I understand correct that these are macros from the C++ standard?

Comment (tcojean) [reply core/test/base/exception_helpers.cpp]: Yes. Well, technically they come from googletest: https://github.com/google/googletest/blob/50f1a77955bde27cf49173c4133688d61f201e85/googletest/docs/advanced.md#exception-assertions

**Comment by tcojean** [comment]
@thoasm no there is no script, this is a bit too hard to do with a script, so I do it with the powerful project-wide replace in emacs.

Nonetheless it's better and safer if the other MRs are merged before this, I think.
