### PR TITLE
Unified tests

### LINKED ISSUE #483: Unifying kernel tests
At the moment, all of our non-reference kernel tests are basically the same (except for the templated tests, but I will get to that): We generate some random matrices or load one of the ani matrices, execute each of our kernels, maybe in multiple configurations on reference and the executor we are testing and compare the result for equality or near-equality.

This approach means a lot of code duplication, a lot of potential for inconsistencies and a lot of work in case we need to change an internal kernel interface.

With a very hacky and inaccurate bash one-liner, I looked at the amount of different lines between CUDA and HIP as well as OMP and CUDA/HIP for each test:
<details>

```
> for f in cuda/test/**/*.c*; do echo $f; ff=${f##cuda/}; fff=${ff%%.c*}; c1=$(diff -y --suppress-common-lines $f hip/${fff}.* | grep "^" | wc -l);c2=$(cat $f | wc -l); echo "$c1 / $c2" | bc -l; done
cuda/test/base/exception_helpers.cu
.18072289156626506024
cuda/test/base/math.cu
.07228915662650602409
cuda/test/components/cooperative_groups.cu
.33716475095785440613
cuda/test/components/merging.cu
.13103448275862068965
cuda/test/components/prefix_sum.cu
.03191489361702127659
cuda/test/components/searching.cu
.06530612244897959183
cuda/test/components/sorting.cu
.12056737588652482269
cuda/test/factorization/par_ilu_kernels.cpp
.26011560693641618497
cuda/test/matrix/coo_kernels.cpp
.04580152671755725190
cuda/test/matrix/csr_kernels.cpp
.11893583724569640062
cuda/test/matrix/dense_kernels.cpp
.12231759656652360515
cuda/test/matrix/ell_kernels.cpp
.04624277456647398843
cuda/test/matrix/hybrid_kernels.cpp
.07272727272727272727
cuda/test/matrix/sellp_kernels.cpp
.06060606060606060606
cuda/test/preconditioner/jacobi_kernels.cpp
.13129973474801061007
cuda/test/solver/bicg_kernels.cpp
.12885154061624649859
cuda/test/solver/bicgstab_kernels.cpp
.16713091922005571030
cuda/test/solver/cg_kernels.cpp
.15073529411764705882
cuda/test/solver/cgs_kernels.cpp
.17191977077363896848
cuda/test/solver/fcg_kernels.cpp
.14736842105263157894
cuda/test/solver/gmres_kernels.cpp
.15107913669064748201
cuda/test/solver/ir_kernels.cpp
.13768115942028985507
cuda/test/solver/lower_trs_kernels.cpp
.11695906432748538011
cuda/test/solver/upper_trs_kernels.cpp
.12209302325581395348
cuda/test/stop/criterion_kernels.cpp
.07619047619047619047
cuda/test/stop/residual_norm_reduction_kernels.cpp
.06164383561643835616
cuda/test/utils/assertions_test.cpp
.09638554216867469879
> for f in omp/test/**/*.cpp; do echo $f; ff=${f##omp/}; fff=${ff%%.cpp}; c1=$(diff -y --suppress-common-lines $f cuda/${fff}.* | grep "^" | wc -l);c2=$(cat $f | wc -l); echo "$c1 / $c2" | bc -l; done
omp/test/components/prefix_sum.cpp
.05376344086021505376
omp/test/factorization/par_ilu_kernels.cpp
.30769230769230769230
omp/test/matrix/coo_kernels.cpp
.24444444444444444444
omp/test/matrix/csr_kernels.cpp
.65886939571150097465
omp/test/matrix/dense_kernels.cpp
.56441717791411042944
omp/test/matrix/ell_kernels.cpp
.72398190045248868778
omp/test/matrix/hybrid_kernels.cpp
.07305936073059360730
omp/test/matrix/sellp_kernels.cpp
.47950819672131147540
omp/test/preconditioner/jacobi_kernels.cpp
.08366533864541832669
omp/test/solver/bicg_kernels.cpp
.20000000000000000000
omp/test/solver/bicgstab_kernels.cpp
.15449438202247191011
omp/test/solver/cg_kernels.cpp
.11808118081180811808
omp/test/solver/cgs_kernels.cpp
.14942528735632183908
omp/test/solver/fcg_kernels.cpp
.11619718309859154929
omp/test/solver/gmres_kernels.cpp
.13357400722021660649
omp/test/solver/ir_kernels.cpp
.12213740458015267175
omp/test/solver/lower_trs_kernels.cpp
.44221105527638190954
omp/test/solver/upper_trs_kernels.cpp
.45959595959595959595
omp/test/stop/criterion_kernels.cpp
.11111111111111111111
omp/test/stop/residual_norm_reduction_kernels.cpp
.40983606557377049180
```

</details>
Except for some cases where we actually have different test sets (like omp ELL vs GPU ELL), most of the files have less than 20% differences, and I am sure if we were to look at it more closely, most of these differences would just be the names `omp`, `cuda` or `hip` in the namespaces and executor variables. (and of course some inconsistencies due to the fact that changes were only made to one of the tests, but not matched with the other executors)

Thus I would like to discuss whether you consider it sensible to unify the kernel tests into a single code structure, and if so, what the best approach to implementing this would be.

I'm thinking of a wrapper that amounts to something like

```cpp
ref->run(make_operation(...));
for (auto exec : execs) {
    try {
        exec->run(make_operation(...));
    } catch (NotImplemented...) {}
    ASSERT_*
}
```

This would again cut down on the test runtimes (as I assume the reference implementations are often our bottleneck) and provide additional benefits, like a simple enumeration of missing kernels.
This would also allow us to extend our GPU tests to the templated setting, while still avoiding issues with missing 64bit support in cuSPARSE/hipSPARSE.

I would of course still keep the individual test folders, since there are certain components etc. that are specific to the executors and should only be tested there.

### PR DESCRIPTION
**Pull request by upsj**
This is a big one 😀 Most of our tests are 90% - 100% identical between different executors. In terms of maintenance, I don't think there is value in keeping them separate. If there is specific behavior we need to test, we can+
* do that in an isolated executor-specific test
* #ifdef the test away for other executors or
* test it anyways, since more tests is more good (:

TODO:
- [x] Csr kernel tests

Depends on #1123
Closes #483

### CODE REVIEW

**Comment by upsj** [comment]
format!

**Comment by upsj** [comment]
format!

File: test/stop/criterion_kernels.cpp [hunk 1]
```diff
@@ -30,49 +30,48 @@ THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************<GINKGO LICENSE>*******************************/
 
-#include <ginkgo/core/stop/criterion.hpp>
```
Comment (yhmtsai) [inline test/stop/criterion_kernels.cpp:33]: "core/stop/criterion_kernels.hpp"

File: test/stop/residual_norm_kernels.cpp [hunk 2]
```diff
@@ -0,0 +1,783 @@
...
+    using NormVector = typename TestFixture::NormVector;
+    auto initial_res = gko::initialize<Mtx>({100.0}, this->exec);
+    std::shared_ptr<gko::LinOp> rhs = gko::initialize<Mtx>({10.0}, this->exec);
+    auto criterion =
+        this->factory->generate(nullptr, rhs, nullptr, initial_res.get());
+    auto rel_criterion =
+        this->rel_factory->generate(nullptr, rhs, nullptr, initial_res.get());
+    auto abs_criterion =
+        this->abs_factory->generate(nullptr, rhs, nullptr, initial_res.get());
+    {
```
Comment (yhmtsai) [inline test/stop/residual_norm_kernels.cpp:104]: the following three scope does not share too much common factor, maybe separate them to three test?

File: test/utils/executor.hpp [hunk 3]
```diff
@@ -33,56 +33,93 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
...
-void init_executor(std::shared_ptr<gko::ReferenceExecutor> ref,
-                   std::shared_ptr<gko::CudaExecutor>& exec)
+inline std::shared_ptr<gko::CudaExecutor> init_executor(
+    std::shared_ptr<gko::ReferenceExecutor> ref, gko::CudaExecutor*)
 {
-    ASSERT_GT(gko::CudaExecutor::get_num_devices(), 0);
-    exec = gko::CudaExecutor::create(0, ref);
+    {
+        if (gko::CudaExecutor::get_num_devices() == 0) {
+            throw std::runtime_error{"No suitable HIP devices"};
```
Comment (yhmtsai) [inline test/utils/executor.hpp:76]:
```suggestion
            throw std::runtime_error{"No suitable CUDA devices"};
```

File: test/utils/executor.hpp [hunk 4]
```diff
@@ -33,56 +33,93 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
...
 {
-    exec = gko::OmpExecutor::create();
+    return gko::OmpExecutor::create();
 }
 
 
-void init_executor(std::shared_ptr<gko::ReferenceExecutor> ref,
-                   std::shared_ptr<gko::CudaExecutor>& exec)
+inline std::shared_ptr<gko::CudaExecutor> init_executor(
+    std::shared_ptr<gko::ReferenceExecutor> ref, gko::CudaExecutor*)
```
Comment (yhmtsai) [inline test/utils/executor.hpp:72]: maybe use template type not the dummy pointer?

**Review by yhmtsai — COMMENTED** [review]
thanks for this impressive work

File: core/test/utils.hpp [hunk 5]
```diff
@@ -189,7 +189,8 @@ struct reduction_factor {
     using nc_output = remove_complex<OutputType>;
     using nc_precision = remove_complex<Precision>;
     static constexpr nc_output value{
-        std::numeric_limits<nc_precision>::epsilon() * nc_output{10}};
+        std::numeric_limits<nc_precision>::epsilon() * nc_output{10} *
+        (gko::is_complex<Precision>() ? nc_output{1.4142} : one<nc_output>())};
```
[the remark this answers is not in the document]
Comment (upsj) [reply core/test/utils.hpp:193]: yes, though it was surprisingly complicated to get that value in there, so I hand-wrote it

File: omp/test/stop/residual_norm_kernels.cpp [hunk 6]
```diff
@@ -53,24 +53,24 @@ class ResidualNorm : public ::testing::Test {
 
     ResidualNorm()
     {
-        exec_ = gko::OmpExecutor::create();
```
[the remark this answers is not in the document]
Comment (upsj) [reply omp/test/stop/residual_norm_kernels.cpp:56]: true, forgot to delete it, I had it there for reference

File: reference/test/stop/residual_norm_kernels.cpp [hunk 7]
```diff
@@ -368,7 +368,7 @@ TYPED_TEST(ResidualNorm, SelfCalulatesAndWaitsTillResidualGoal)
         ASSERT_EQ(stop_status.get_data()[0].has_converged(), false);
         ASSERT_EQ(one_changed, false);
 
-        solution->at(0) = rhs_val - r<T>::value * T{0.9} * rhs_norm->at(0);
+        solution->at(0) = rhs_val - r<T>::value * T{0.5} * rhs_norm->at(0);
```
[the remark this answers is not in the document]
Comment (upsj) [reply reference/test/stop/residual_norm_kernels.cpp:371]: It's related to the sqrt(2) changes in `r::value`

File: test/components/prefix_sum_kernels.cpp [hunk 8]
```diff
@@ -89,17 +82,17 @@ class PrefixSum : public ::testing::Test {
...
 
 
-TYPED_TEST(PrefixSum, TrivialCasesEqualReference)
+TYPED_TEST(PrefixSum, EqualsReference)
 {
-    this->test(0);
-    this->test(1);
+    using gko::size_type;
+    for (auto size :
+         {size_type{0}, size_type{1}, size_type{100}, this->total_size}) {
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/components/prefix_sum_kernels.cpp:89]: good idea!

File: test/factorization/par_ilu_kernels.cpp [hunk 9]
```diff
@@ -0,0 +1,312 @@
...
+    std::default_random_engine rand_engine;
+    std::shared_ptr<const Csr> mtx;
+    std::shared_ptr<const Csr> dmtx;
+
+    ParIlu() : rand_engine(18)
+    {
+        std::string file_name(gko::matrices::location_ani4_mtx);
+        auto input_file = std::ifstream(file_name, std::ios::in);
+        auto mtx_temp = gko::read<Csr>(input_file, ref);
+        auto dmtx_temp = gko::clone(exec, mtx_temp);
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/factorization/par_ilu_kernels.cpp:79]: done

File: test/matrix/csr_kernels2.cpp [hunk 10]
```diff
@@ -79,41 +82,74 @@ class Csr : public ::testing::Test {
...
+    {
+#ifdef GKO_COMPILING_OMP
+        throw std::runtime_error{"We shouldn't be testing this"};
+#else
+        strategy = std::make_shared<typename Mtx::automatical>(exec);
+#endif
+    }
+
+    template <typename Mtx>
+    void set_up_strategy(std::shared_ptr<typename Mtx::sparselib>& strategy)
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:121]: some strategies take a statically typed executor of restricted type, some don't take an executor at all, we need a generic way to set them up

File: test/matrix/csr_kernels2.cpp [hunk 11]
```diff
@@ -79,41 +82,74 @@ class Csr : public ::testing::Test {
...
-    {
-        ASSERT_GT(gko::DpcppExecutor::get_num_devices("all"), 0);
-        ref = gko::ReferenceExecutor::create();
-        dpcpp = gko::DpcppExecutor::create(0, ref);
-    }
-
-    void TearDown()
+    template <typename MtxType>
+    std::unique_ptr<MtxType> gen_mtx(int num_rows, int num_cols,
+                                     int min_nnz_row, int max_nnz_row)
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:87]: that's essentially what we're doing here, only you can't default a parameter to another value

File: test/matrix/csr_kernels2.cpp [hunk 12]
```diff
@@ -964,4 +1199,55 @@ TEST_F(Csr, CreateSubMatrixIsEquivalentToRef)
 }
 
 
-}  // namespace
+#ifndef GKO_COMPILING_DPCPP
+
+
+TEST_F(Csr, CanDetectMissingDiagonalEntry)
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:1205]: I added them to https://github.com/ginkgo-project/ginkgo/issues/286

File: test/matrix/ell_kernels.cpp [hunk 13]
```diff
@@ -450,7 +433,7 @@ TEST_F(Ell, AdvancedByAtomicApplyIsEquivalentToRef)
     mtx->apply(alpha.get(), y.get(), beta.get(), expected.get());
     dmtx->apply(dalpha.get(), dy.get(), dbeta.get(), dresult.get());
 
-    GKO_ASSERT_MTX_NEAR(dresult, expected, r<vtype>::value);
+    GKO_ASSERT_MTX_NEAR(dresult, expected, r<vtype>::value * 10);
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/ell_kernels.cpp:436]: I think it was CUDA, but don't quote me on that. With the atomics, the results are a bit flaky, so I wanted to add some slack

File: test/matrix/ell_kernels.cpp [hunk 14]
```diff
@@ -432,14 +412,17 @@ TEST_F(Ell, MixedAdvancedApplyWithStrideToDenseMatrixIsEquivalentToRef3)
 }
 
 
+#ifndef GKO_COMPILING_OMP
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/ell_kernels.cpp:415]: good point, we can leave them in

File: test/matrix/fbcsr_kernels.cpp [hunk 15]
```diff
@@ -181,19 +165,19 @@ TYPED_TEST(Fbcsr, SpmvIsEquivalentToRefSorted)
...
-    rand_cuda->copy_from(gko::lend(this->rsorted_ref));
-    auto x_ref = Dense::create(
-        this->ref, gko::dim<2>(this->rsorted_ref->get_size()[1], 1));
+    auto drand = Mtx::create(this->exec);
+    drand->copy_from(gko::lend(this->rsorted));
+    auto x_ref =
+        Dense::create(this->ref, gko::dim<2>(this->rsorted->get_size()[1], 1));
     this->generate_sin(x_ref.get());
-    auto x_cuda = Dense::create(this->cuda);
+    auto x_cuda = Dense::create(this->exec);
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/fbcsr_kernels.cpp:173]: done

File: test/matrix/dense_kernels.cpp [hunk 16]
```diff
@@ -135,17 +121,23 @@ class Dense : public ::testing::Test {
         dc_y = gko::clone(exec, c_y);
         dalpha = gko::clone(exec, alpha);
         dc_alpha = gko::clone(exec, c_alpha);
+        result = Mtx::create(ref, gko::dim<2>{1, num_vecs});
+        dresult = Mtx::create(exec, gko::dim<2>{1, num_vecs});
     }
 
     void set_up_apply_data()
     {
         x = gen_mtx<Mtx>(40, 25);
```
Comment (fritzgoebel) [inline test/matrix/dense_kernels.cpp:130]: That's the size from the OMP kernels. I'd suggest taking the bigger size from the other executors to include at least two warps everywhere

File: test/preconditioner/jacobi_kernels.cpp [hunk 17]
```diff
@@ -323,20 +307,23 @@ TEST_F(Jacobi, HipPreconditionerEquivalentToRefWithBlockSize32Unsorted)
 }
 
 
-#if GINKGO_HIP_PLATFORM_HCC
-TEST_F(Jacobi, HipPreconditionerEquivalentToRefWithBlockSize64)
+#ifdef GKO_COMPILING_HIP
```
Comment (pratikvn) [inline test/preconditioner/jacobi_kernels.cpp:310]: Do we not test hip on CUDA GPUs anymore ?

File: test/matrix/csr_kernels2.cpp [hunk 18]
```diff
@@ -240,9 +275,35 @@ TEST_F(Csr, SimpleApplyIsEquivalentToRefWithOnemkl)
 }
 
 
-TEST_F(Csr, SimpleApplyIsEquivalentToRefWithOnemklUnsorted)
```
Comment (pratikvn) [inline test/matrix/csr_kernels2.cpp:243]: Isnt this this specfic to DPCPP ?

File: test/matrix/csr_kernels2.cpp [hunk 19]
```diff
@@ -438,16 +519,77 @@ TEST_F(Csr, SimpleApplyToCsrMatrixIsEquivalentToRef)
...
+    mtx1->apply(mtx2.get(), square_mtx.get());
+    dmtx1->apply(dmtx2.get(), square_dmtx.get());
+
+    GKO_ASSERT_MTX_EQ_SPARSITY(square_dmtx, square_mtx);
+    GKO_ASSERT_MTX_NEAR(square_dmtx, square_mtx, 1e-14);
+    ASSERT_TRUE(square_dmtx->is_sorted_by_column_index());
+}
+
+
+// TODO: broken in ROCm <= 4.5
```
Comment (pratikvn) [inline test/matrix/csr_kernels2.cpp:559]: That is due to a hipsparse bug ? And in case it works in 5.x, then maybe only disable it for 4.5 and not for all HIP versions ?

**Review by pratikvn — COMMENTED** [review]
Really nice work! A few comments and questions.

File: test/preconditioner/jacobi_kernels.cpp (hunk 17 above)
Comment (upsj) [reply test/preconditioner/jacobi_kernels.cpp:310]: Blocksize 64 is only enabled for ROCm, we check the warp size in the test body

File: test/matrix/csr_kernels2.cpp (hunk 18 above)
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:243]: We test the behavior in SimpleApplyIsEquivalentToRefWithSparselibUnsorted

File: test/matrix/csr_kernels2.cpp (hunk 19 above)
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:559]: Yes, I'll add a workaround later, but we didn't have this test for HIP before, so it's not a regression

File: test/solver/cb_gmres_kernels.cpp [hunk 20]
```diff
@@ -259,15 +236,15 @@ class CbGmres : public ::testing::Test {
 };
 
 
-TEST_F(CbGmres, DpcppCbGmresInitialize1IsEquivalentToRef)
+TEST_F(CbGmres, CbGmresInitialize1IsEquivalentToRef)
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/solver/cb_gmres_kernels.cpp:239]: The executor is always visible from context, e.g. ctest output or which binary you launched. Most tests don't have this prefix

**Review by fritzgoebel — COMMENTED** [review]
Thanks for tackling this!
It is a lot to go through so I'd suggest a few of us do it.

File: reference/test/stop/residual_norm_kernels.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (upsj) [reply reference/test/stop/residual_norm_kernels.cpp:371]: no, because I relaxed the complex error bounds to include a sqrt(2) factor

File: test/solver/idr_kernels.cpp [hunk 21]
```diff
@@ -42,46 +43,44 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #include <ginkgo/core/base/array.hpp>
 #include <ginkgo/core/base/exception.hpp>
 #include <ginkgo/core/base/executor.hpp>
+#include <ginkgo/core/base/mtx_io.hpp>
+#include <ginkgo/core/matrix/csr.hpp>
 #include <ginkgo/core/matrix/dense.hpp>
+#include <ginkgo/core/solver/bicgstab.hpp>
+#include <ginkgo/core/solver/gmres.hpp>
```
Comment (MarcelKoch) [inline test/solver/idr_kernels.cpp:50]: unused
```suggestion
```

File: test/solver/multigrid_kernels.cpp [hunk 22]
```diff
@@ -42,36 +42,21 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #include <ginkgo/core/base/exception.hpp>
 #include <ginkgo/core/base/executor.hpp>
 #include <ginkgo/core/matrix/dense.hpp>
+#include <ginkgo/core/solver/multigrid.hpp>
```
Comment (MarcelKoch) [inline test/solver/multigrid_kernels.cpp:45]: surprisingly(?) unused
```suggestion
```

File: test/stop/criterion_kernels.cpp [hunk 23]
```diff
@@ -30,49 +30,48 @@ THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
...
-
 #include <gtest/gtest.h>
 
 
+#include <ginkgo/core/stop/criterion.hpp>
 #include <ginkgo/core/stop/iteration.hpp>
 
 
-namespace {
+#include "core/test/utils.hpp"
```
Comment (MarcelKoch) [inline test/stop/criterion_kernels.cpp:40]: unused
```suggestion
```

**Review by MarcelKoch — APPROVED** [review]
looks very good. I've left some smaller remarks. I guess we need to see if the coverage changes due to this.
I would also suggest getting more than 2 approvals, because a single person won't find all issues that might be hiding somewhere.

File: test/factorization/par_ilut_kernels.cpp [hunk 24]
```diff
@@ -55,31 +55,29 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
...
 protected:
     using value_type =
         typename std::tuple_element<0, decltype(ValueIndexType())>::type;
     using index_type =
         typename std::tuple_element<1, decltype(ValueIndexType())>::type;
     using Dense = gko::matrix::Dense<value_type>;
+    using ComplexDense = gko::matrix::Dense<std::complex<value_type>>;
     using Coo = gko::matrix::Coo<value_type, index_type>;
     using Csr = gko::matrix::Csr<value_type, index_type>;
+    using ComplexCsr = gko::matrix::Csr<std::complex<value_type>, index_type>;
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/factorization/par_ilut_kernels.cpp:72]: true, this is no longer necessary, with the tests being fully templated now

File: core/test/utils.hpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (upsj) [reply core/test/utils.hpp:193]: nice suggestion, thanks!

File: test/components/prefix_sum_kernels.cpp [hunk 25]
```diff
@@ -44,23 +44,17 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #include <ginkgo/core/base/array.hpp>
 
 
-#include "core/test/utils.hpp"
-
-
-namespace {
+#include "cuda/test/utils.hpp"
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/components/prefix_sum_kernels.cpp:47]: no, that was leftover from the original :)

File: test/matrix/csr_kernels2.cpp [hunk 26]
```diff
@@ -928,32 +1078,124 @@ TEST_F(Csr, ComputeSubmatrixIsEquivalentToRef)
...
+    gko::index_set<IndexType> drset(this->exec, rset);
+    gko::index_set<IndexType> dcset(this->exec, cset);
+    auto size = this->mtx2->get_size();
+    auto row_nnz = gko::array<int>(this->ref, rset.get_num_elems() + 1);
+    row_nnz.fill(gko::zero<int>());
+    auto drow_nnz = gko::array<int>(this->exec, row_nnz);
+
+    gko::kernels::reference::csr::calculate_nonzeros_per_row_in_index_set(
+        this->ref, this->mtx2.get(), rset, cset, row_nnz.get_data());
+    gko::kernels::omp::csr::calculate_nonzeros_per_row_in_index_set(
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:1125]: great catch!

File: test/stop/criterion_kernels.cpp (hunk 23 above)
Comment (upsj) [reply test/stop/criterion_kernels.cpp:40]: curious how you caught that one. Did you use a tool? It's definitely not obvious!

File: test/matrix/csr_kernels2.cpp [hunk 27]
```diff
@@ -408,9 +459,39 @@ TEST_F(Csr, AdvancedApplyToDenseMatrixIsEquivalentToRefWithMergePath)
 }
 
 
+TEST_F(Csr, OneAutomaticalWorksWithDifferentMatrices)
+{
+    auto automatical = std::make_shared<Mtx::automatical>(exec);
+#ifdef GKO_COMPILING_CUDA
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:465]: We're not very consistent about this surprisingly, but most cases use `#ifdef`, not `#if defined`:

```bash
grep -rh "#if" test | sort | uniq -c
      2 #if !(GINKGO_COMMON_SINGLE_MODE)
     25 #if GINKGO_COMMON_SINGLE_MODE
      1 #if GKO_HAVE_PAPI_SDE
      3 #if HAS_REFERENCE
      2 #if defined(GKO_COMPILING_CUDA) || defined(GKO_COMPILING_HIP) || \
      1 #if defined(GKO_COMPILING_OMP) || defined(GKO_COMPILING_CUDA) || \
      1 #if defined(HAS_CUDA)
      1 #if defined(HAS_CUDA) || defined(HAS_HIP)
      2 #if defined(HAS_HIP) || defined(HAS_CUDA)
      6 #ifdef GINKGO_FAST_TESTS
      6 #ifdef GKO_COMPILING_CUDA
      1 #ifdef GKO_COMPILING_DPCPP
      6 #ifdef GKO_COMPILING_HIP
      4 #ifdef GKO_COMPILING_OMP
      2 #ifndef GKO_COMPILING_DPCPP
      2 #ifndef GKO_COMPILING_HIP
      1 #ifndef GKO_COMPILING_OMP
      1 #ifndef GKO_TEST_UTILS_EXECUTOR_HPP_
```

File: test/components/absolute_array_kernels.cpp [hunk 28]
```diff
@@ -48,43 +48,27 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
...
-
-
-class AbsoluteArray : public ::testing::Test {
+class AbsoluteArray : public CommonTestFixture {
 protected:
 #if GINKGO_COMMON_SINGLE_MODE
     using value_type = float;
 #else
     using value_type = double;
 #endif
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/components/absolute_array_kernels.cpp:57]: good point!

File: test/stop/criterion_kernels.cpp (hunk 23 above)
Comment (MarcelKoch) [reply test/stop/criterion_kernels.cpp:40]: I just trust clion on these kinds of things

File: core/test/utils.hpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (upsj) [reply core/test/utils.hpp:194]: unfortunately this doesn't work, because it needs to be constexpr

File: test/preconditioner/isai_kernels.cpp [hunk 29]
```diff
@@ -476,180 +464,177 @@ TEST_F(Isai, HipIsaiGeneratePartialExcessIsEquivalentToRef)
...
+TEST_F(Isai, IsaiScatterExcessSolutionSpdIsEquivalentToRef)
 {
     initialize_data(matrix_type::spd, 100, 64);
     const auto num_rows = mtx->get_size()[0];
     gko::array<index_type> a1(ref, num_rows + 1);
     auto a2 = a1;
     gko::kernels::reference::isai::generate_general_inverse(
-        ref, mtx.get(), inverse.get(), a1.get_data(), a2.get_data(), true);
-    gko::array<index_type> da1(hip, a1);
+        ref, mtx.get(), inverse.get(), a1.get_data(), a2.get_data(), false);
```
Comment (yhmtsai) [inline test/preconditioner/isai_kernels.cpp:598]: the next excess solution also uses true. Should it be true or false?

File: test/preconditioner/isai_kernels.cpp [hunk 30]
```diff
@@ -275,43 +263,43 @@ TEST_F(Isai, HipIsaiGenerateUinverseLongIsEquivalentToRef)
...
         ref, mtx.get(), inverse.get(), a1.get_data(), a2.get_data(), false);
-    gko::kernels::hip::isai::generate_general_inverse(
-        hip, d_mtx.get(), d_inverse.get(), da1.get_data(), da2.get_data(),
+    gko::kernels::EXEC_NAMESPACE::isai::generate_general_inverse(
+        exec, d_mtx.get(), d_inverse.get(), da1.get_data(), da2.get_data(),
         false);
 
     GKO_ASSERT_MTX_EQ_SPARSITY(inverse, d_inverse);
-    GKO_ASSERT_MTX_NEAR(inverse, d_inverse, 10 * r<value_type>::value);
+    GKO_ASSERT_MTX_NEAR(inverse, d_inverse, 100 * r<value_type>::value);
```
Comment (yhmtsai) [inline test/preconditioner/isai_kernels.cpp:282]: maybe need to be careful?

File: test/solver/gmres_kernels.cpp [hunk 31]
```diff
@@ -43,46 +43,46 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
...
-            ASSERT_NO_THROW(dpcpp->synchronize());
-        }
+        mtx = gen_mtx(123, 123);
+        d_mtx = gko::clone(exec, mtx);
+        exec_gmres_factory =
+            Solver::build()
+                .with_criteria(
+                    gko::stop::Iteration::build().with_max_iters(246u).on(exec),
+                    gko::stop::ResidualNorm<value_type>::build()
+                        .with_reduction_factor(value_type{1e-15})
```
Comment (yhmtsai) [inline test/solver/gmres_kernels.cpp:74]: still surprised at float germs can use 1e-15 as reduction_factor?

**Review by yhmtsai — APPROVED** [review]
the excess system in Isai uses true/false in different tests.
I am not in favor of that the init_executor uses overload by passing nullptr not template to choose which implementation.

File: test/matrix/csr_kernels2.cpp [hunk 32]
```diff
@@ -188,309 +218,416 @@ class Csr : public ::testing::Test {
...
     auto trans = mtx->transpose();
     auto d_trans = dmtx->transpose();
 
     mtx->apply(trans.get(), square_mtx.get());
     dmtx->apply(d_trans.get(), square_dmtx.get());
 
-    GKO_ASSERT_MTX_NEAR(square_dmtx, square_mtx, 1e-14);
+    GKO_ASSERT_MTX_NEAR(square_dmtx, square_mtx, r<value_type>::value);
+    GKO_ASSERT_MTX_EQ_SPARSITY(square_dmtx, square_mtx);
+    ASSERT_TRUE(square_dmtx->is_sorted_by_column_index());
```
[the remark this answers is not in the document]
Comment (upsj) [reply test/matrix/csr_kernels2.cpp:513]: all the assertions take the matrix by const pointer, so this shouldn't be an issue

File: test/preconditioner/isai_kernels.cpp (hunk 30 above)
Comment (upsj) [reply test/preconditioner/isai_kernels.cpp:282]: I like to increase the error bounds with big margins to make sure we don't have any flaky tests if some compiler optimizations change the evaluation order. Do you think this is an issue here?

File: test/preconditioner/isai_kernels.cpp (hunk 29 above)
Comment (upsj) [reply test/preconditioner/isai_kernels.cpp:598]: it should stay `true`, good catch!

**Review by fritzgoebel — APPROVED** [review]
LGTM!

**Comment by upsj** [comment]
format!

File: test/solver/gmres_kernels.cpp (hunk 31 above)
Comment (yhmtsai) [reply test/solver/gmres_kernels.cpp:74]: yes, unit roundoff here. it's hard to reach that when in float.
I see, I miss the iteration criterion.

File: test/preconditioner/isai_kernels.cpp (hunk 30 above)
Comment (yhmtsai) [reply test/preconditioner/isai_kernels.cpp:282]: I do not know actually.
Without knowing the testing problem, I can somehow accept 10 r as rounding issue. 100 r will be a little higher such that I start wondering whether there's something wrong or the wrong codes may also pass the test
