### PR TITLE
Make preconditioners transposable

### LINKED ISSUE #477: BiCG does not work with preconditioners
In the ParILUT branch (where I added BiCG to the solver benchmark), we get the following error

```
> echo '[{"filename":"../matrices/test/ani4.mtx", "optimal": {"spmv":"csr"}}]' | benchmark/solver/solver -sovers bicg -preconditioners ilu

what(): /ginkgo/include/ginkgo/core/base/utils.hpp:318: Operation as does not support parameters of type gko::LinOp const*
```

### PR DESCRIPTION
**Pull request by upsj**
This PR makes all of our preconditioners and solvers transposable. For composite preconditioners, this works by adding a `transposed_type` alias to all transposable LinOps, so we can convert between LowerTrs/Isai and UpperTrs/Isai

TODO:
- [x] Add tests
- [x] Implement Jacobi transpose

Fixes #477

### CODE REVIEW

File: core/solver/lower_trs.cpp [hunk 1]
```diff
@@ -61,6 +62,38 @@ GKO_REGISTER_OPERATION(solve, lower_trs::solve);
...
+{
+    std::unique_ptr<transposed_type> transposed{
+        new transposed_type{this->get_executor()}};
+    transposed->set_size(gko::transpose(this->get_size()));
+    transposed->system_matrix_ = share(as<matrix::Csr<ValueType, IndexType>>(
+        this->get_system_matrix()->transpose()));
+    transposed->parameters_.num_rhs = this->parameters_.num_rhs;
+    transposed->init_trs_solve_struct();
+    transposed->generate();
+
```
Comment (yhmtsai) [inline core/solver/lower_trs.cpp:76]: Why to use factory build in the CG/FCG/etc... but create empty, then change the parameter in the LowerTrs?

File: omp/test/preconditioner/jacobi_kernels.cpp [hunk 2]
```diff
@@ -562,6 +588,35 @@ TEST_F(Jacobi, OmpPreconditionerEquivalentToRefWithAdaptivePrecision)
...
+{
+    initialize_data({0, 11, 24, 33, 45, 55, 67, 70, 80, 92, 100},
+                    {sp, sp, dp, dp, tp, tp, qp, qp, hp, dp, up}, {}, 13, 97,
+                    99);
+
+    auto bj = bj_factory->generate(mtx);
+    auto d_bj = d_bj_factory->generate(mtx);
+
+    GKO_ASSERT_MTX_NEAR(gko::as<Bj>(d_bj->transpose()),
+                        gko::as<Bj>(bj->transpose()), 1e-1);
```
Comment (yhmtsai) [inline omp/test/preconditioner/jacobi_kernels.cpp:601]: In this test, 1e-1 comes from the `generate` not the transpose.
maybe both use reference generated result and do transpose on device/ref. The result should be the same.

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 3]
```diff
@@ -326,6 +326,122 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+    GKO_EXPECT_NEAR(b2[1 + 0 * p], T{8.0 / 48.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b2[2 + 0 * p], T{4.0 / 48.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b2[0 + 1 * p], T{4.0 / 48.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b2[1 + 1 * p], T{16.0 / 48.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b2[2 + 1 * p], T{8.0 / 48.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b2[0 + 2 * p], T{1.0 / 48.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b2[1 + 2 * p], T{4.0 / 48.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b2[2 + 2 * p], T{14.0 / 48.0}, r<T>::value);
+}
+
```
Comment (yhmtsai) [inline reference/test/preconditioner/jacobi_kernels.cpp:355]:
```suggestion


```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 4]
```diff
@@ -326,6 +326,122 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
```
Comment (yhmtsai) [inline reference/test/preconditioner/jacobi_kernels.cpp:413]:
```suggestion


```

File: core/solver/cg.cpp [hunk 5]
```diff
@@ -59,6 +59,20 @@ GKO_REGISTER_OPERATION(step_2, cg::step_2);
 }  // namespace cg
 
 
+template <typename ValueType>
+std::unique_ptr<LinOp> Cg<ValueType>::transpose() const
+{
+    return this->clone();
```
[the remark this answers is not in the document]
Comment (upsj) [reply core/solver/cg.cpp:65]: yes, exactly. Same for conj_transpose

File: include/ginkgo/core/preconditioner/jacobi.hpp [hunk 6]
```diff
@@ -489,7 +495,7 @@ class Jacobi : public EnableLinOp<Jacobi<ValueType, IndexType>>,
     explicit Jacobi(const Factory *factory,
                     std::shared_ptr<const LinOp> system_matrix)
         : EnableLinOp<Jacobi>(factory->get_executor(),
-                              transpose(system_matrix->get_size())),
+                              gko::transpose(system_matrix->get_size())),
```
[the remark this answers is not in the document]
Comment (upsj) [reply include/ginkgo/core/preconditioner/jacobi.hpp:498]: Yes, since now there is a transpose(...) member function, that gets found for some reason

File: include/ginkgo/core/preconditioner/jacobi.hpp [hunk 7]
```diff
@@ -107,8 +107,8 @@ struct block_interleaved_storage_scheme {
      *        blocks is not known, for a special input `size_type{} - 1`
      *        the method returns `0` to avoid overallocation of memory.
      */
-    GKO_ATTRIBUTES size_type compute_storage_space(size_type num_blocks) const
-        noexcept
+    GKO_ATTRIBUTES size_type
+    compute_storage_space(size_type num_blocks) const noexcept
```
[the remark this answers is not in the document]
Comment (upsj) [reply include/ginkgo/core/preconditioner/jacobi.hpp:111]: Yes, that's clang-format 10, I had it chosen accidentally

File: omp/test/preconditioner/jacobi_kernels.cpp (hunk 2 above)
Comment (upsj) [reply omp/test/preconditioner/jacobi_kernels.cpp:601]: So you mean d_bj->copy_from(bj) instead of generating it?

Comment (yhmtsai) [reply omp/test/preconditioner/jacobi_kernels.cpp:601]: Yes

File: omp/test/preconditioner/jacobi_kernels.cpp [hunk 8]
```diff
@@ -562,6 +590,37 @@ TEST_F(Jacobi, OmpPreconditionerEquivalentToRefWithAdaptivePrecision)
...
+    initialize_data({0, 11, 24, 33, 45, 55, 67, 70, 80, 92, 100},
+                    {sp, sp, dp, dp, tp, tp, qp, qp, hp, dp, up}, {}, 13, 97,
+                    99);
+
+    auto bj = bj_factory->generate(mtx);
+    auto d_bj = d_bj_factory->generate(mtx);
+    d_bj->copy_from(bj.get());
+
+    GKO_ASSERT_MTX_NEAR(gko::as<Bj>(d_bj->transpose()),
+                        gko::as<Bj>(bj->transpose()), 1e-1);
```
Comment (yhmtsai) [inline omp/test/preconditioner/jacobi_kernels.cpp:604]: forget to change the error bound?

File: cuda/test/preconditioner/jacobi_kernels.cpp [hunk 9]
```diff
@@ -325,6 +325,34 @@ TEST_F(Jacobi, CudaPreconditionerEquivalentToRefWithMPW)
...
+{
+    initialize_data({0, 11, 24, 33, 45, 55, 67, 70, 80, 92, 100}, {}, {}, 13,
+                    97, 99);
+
+    auto bj = bj_factory->generate(mtx);
+    auto d_bj = d_bj_factory->generate(mtx);
+    d_bj->copy_from(bj.get());
+
+    GKO_ASSERT_MTX_NEAR(gko::as<Bj>(d_bj->transpose()),
+                        gko::as<Bj>(bj->transpose()), 1e-13);
```
Comment (yhmtsai) [inline cuda/test/preconditioner/jacobi_kernels.cpp:338]: use 1e-14 in omp but 1e-13 in cuda/hip. Does it fail when using 1e-14?

File: cuda/test/preconditioner/jacobi_kernels.cpp [hunk 10]
```diff
@@ -325,6 +325,34 @@ TEST_F(Jacobi, CudaPreconditionerEquivalentToRefWithMPW)
 }
 
 
+TEST_F(Jacobi, CudaTransposedPreconditionerEquivalentToRefWithMPW)
+{
+    initialize_data({0, 11, 24, 33, 45, 55, 67, 70, 80, 92, 100}, {}, {}, 13,
+                    97, 99);
+
+    auto bj = bj_factory->generate(mtx);
+    auto d_bj = d_bj_factory->generate(mtx);
```
Comment (yhmtsai) [inline cuda/test/preconditioner/jacobi_kernels.cpp:334]: I prefer generating `d_bj` on empty matrix. how do you think?

Comment (upsj) [reply cuda/test/preconditioner/jacobi_kernels.cpp:334]: Do you think this would make a difference? I was just lazy, as usual :laughing:

File: cuda/test/preconditioner/jacobi_kernels.cpp (hunk 9 above)
Comment (upsj) [reply cuda/test/preconditioner/jacobi_kernels.cpp:338]: no, 1e-14 still works :)

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 11]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+    auto bj = gko::as<Bj>(tmp_bj->transpose());
+
+    auto scheme = bj->get_storage_scheme();
+    auto p = scheme.get_stride();
+    auto b1 = bj->get_blocks() + scheme.get_global_block_offset(0);
+    GKO_EXPECT_NEAR(b1[0 + 0 * p], T{4.0 / 14.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b1[1 + 0 * p], T{2.0 / 14.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b1[0 + 1 * p], T{1.0 / 14.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b1[1 + 1 * p], T{4.0 / 14.0}, r<T>::value);
+
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:344]: this empty line should be removed since the `auto b2` below is already making it obvious that a different block is tesed.
```suggestion
```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 12]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
 }
 
 
+TYPED_TEST(Jacobi, CanTransposeDiagonalBlocks)
+{
+    using T = typename TestFixture::value_type;
+    using Bj = typename TestFixture::Bj;
+    auto tmp_bj = this->bj_factory->generate(this->mtx);
+    auto bj = gko::as<Bj>(tmp_bj->transpose());
+
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:336]: This should be in its own `A` block (Act) since this is what you test.
```suggestion

    auto bj = gko::as<Bj>(tmp_bj->transpose());

```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 13]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+
+TYPED_TEST(Jacobi, CanTransposeDiagonalBlocksWithAdaptivePrecision)
+{
+    using T = typename TestFixture::value_type;
+    using Bj = typename TestFixture::Bj;
+    auto half_tol = std::sqrt(r<T>::value);
+    auto tmp_bj = this->adaptive_bj_factory->generate(this->mtx);
+    auto bj = gko::as<Bj>(tmp_bj->transpose());
+
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:365]:
```suggestion

    auto bj = gko::as<Bj>(tmp_bj->transpose());

```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 14]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+    auto scheme = bj->get_storage_scheme();
+    auto p = scheme.get_stride();
+    using reduced = ::gko::reduce_precision<T>;
+    auto b1 = reinterpret_cast<const reduced *>(
+        bj->get_blocks() + scheme.get_global_block_offset(0));
+    GKO_EXPECT_NEAR(b1[0 + 0 * p], reduced{4.0 / 14.0}, half_tol);
+    GKO_EXPECT_NEAR(b1[1 + 0 * p], reduced{2.0 / 14.0}, half_tol);
+    GKO_EXPECT_NEAR(b1[0 + 1 * p], reduced{1.0 / 14.0}, half_tol);
+    GKO_EXPECT_NEAR(b1[1 + 1 * p], reduced{4.0 / 14.0}, half_tol);
+
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:375]:
```suggestion
```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 15]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+}
+
+
+TYPED_TEST(Jacobi, CanConjTransposeDiagonalBlocks)
+{
+    using T = typename TestFixture::value_type;
+    using Bj = typename TestFixture::Bj;
+    auto tmp_bj = this->bj_factory->generate(this->mtx);
+    auto bj = gko::as<Bj>(tmp_bj->conj_transpose());
+
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:395]:
```suggestion

    auto bj = gko::as<Bj>(tmp_bj->conj_transpose());

```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 16]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+    auto scheme = bj->get_storage_scheme();
+    auto p = scheme.get_stride();
+    auto b1 = bj->get_blocks() + scheme.get_global_block_offset(0);
+    GKO_EXPECT_NEAR(b1[0 + 0 * p], T{4.0 / 14.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b1[1 + 0 * p], T{2.0 / 14.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b1[0 + 1 * p], T{1.0 / 14.0}, r<T>::value);
+    GKO_EXPECT_NEAR(b1[1 + 1 * p], T{4.0 / 14.0}, r<T>::value);
+
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:403]:
```suggestion
```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 17]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+}
+
+
+TYPED_TEST(Jacobi, CanConjTransposeDiagonalBlocksWithAdaptivePrecision)
+{
+    using T = typename TestFixture::value_type;
+    using Bj = typename TestFixture::Bj;
+    auto half_tol = std::sqrt(r<T>::value);
+    auto tmp_bj = this->adaptive_bj_factory->generate(this->mtx);
+    auto bj = gko::as<Bj>(tmp_bj->conj_transpose());
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:423]:
```suggestion

    auto bj = gko::as<Bj>(tmp_bj->conj_transpose());
```

File: reference/test/preconditioner/jacobi_kernels.cpp [hunk 18]
```diff
@@ -326,6 +327,124 @@ TYPED_TEST(Jacobi, InvertsDiagonalBlocksWithAdaptivePrecision)
...
+    auto scheme = bj->get_storage_scheme();
+    auto p = scheme.get_stride();
+    using reduced = ::gko::reduce_precision<T>;
+    auto b1 = reinterpret_cast<const reduced *>(
+        bj->get_blocks() + scheme.get_global_block_offset(0));
+    GKO_EXPECT_NEAR(b1[0 + 0 * p], reduced{4.0 / 14.0}, half_tol);
+    GKO_EXPECT_NEAR(b1[1 + 0 * p], reduced{2.0 / 14.0}, half_tol);
+    GKO_EXPECT_NEAR(b1[0 + 1 * p], reduced{1.0 / 14.0}, half_tol);
+    GKO_EXPECT_NEAR(b1[1 + 1 * p], reduced{4.0 / 14.0}, half_tol);
+
```
Comment (thoasm) [inline reference/test/preconditioner/jacobi_kernels.cpp:434]:
```suggestion
```

File: reference/test/solver/upper_trs_kernels.cpp [hunk 19]
```diff
@@ -205,4 +205,32 @@ TYPED_TEST(UpperTrs, SolvesBigDenseSystem)
...
+{
+    using Mtx = typename TestFixture::Mtx;
+    using value_type = typename TestFixture::value_type;
+    std::shared_ptr<Mtx> b = gko::initialize<Mtx>({4.0, 2.0, 3.0}, this->exec);
+    auto x = gko::initialize<Mtx>({0.0, 0.0, 0.0}, this->exec);
+    auto solver = this->upper_trs_factory->generate(this->mtx);
+
+    solver->conj_transpose()->apply(b.get(), x.get());
+
+    GKO_ASSERT_MTX_NEAR(x, l({4.0, -10.0, 19.0}), r<value_type>::value);
```
Comment (thoasm) [inline reference/test/solver/upper_trs_kernels.cpp:232]: I just want to mention here that for all `conj_transpose`, we don't really test if the conjugation actually works since we don't have complex test matrices for our solvers yet.

File: core/base/combination.cpp [hunk 20]
```diff
@@ -59,6 +59,45 @@ inline void initialize_scalars(std::shared_ptr<const Executor> exec,
...
 
 
+template <typename ValueType>
+std::unique_ptr<LinOp> Combination<ValueType>::transpose() const
+{
+    auto transposed = Combination<ValueType>::create(this->get_executor());
+    transposed->set_size(gko::transpose(this->get_size()));
+    // copy coefficients
+    for (auto &coef : get_coefficients()) {
+        transposed->coefficients_.push_back(share(as<LinOp>(coef->clone())));
```
[the remark this answers is not in the document]
Comment (upsj) [reply core/base/combination.cpp:69]: Good point!

File: cuda/test/preconditioner/jacobi_kernels.cpp (hunk 10 above)
Comment (yhmtsai) [reply cuda/test/preconditioner/jacobi_kernels.cpp:334]: only for less testing time? I do not consider it too seriously. I am fine with current implementation

File: core/preconditioner/isai.cpp [hunk 21]
```diff
@@ -205,6 +205,34 @@ void Isai<IsaiType, ValueType, IndexType>::generate_inverse(
...
 
+
+template <isai_type IsaiType, typename ValueType, typename IndexType>
+std::unique_ptr<LinOp> Isai<IsaiType, ValueType, IndexType>::transpose() const
+{
+    std::unique_ptr<transposed_type> transp{
+        new transposed_type{this->get_executor()}};
+    transp->set_size(gko::transpose(this->get_size()));
+    transp->approximate_inverse_ =
+        share(as<Csr>(this->get_approximate_inverse()->transpose()));
```
[the remark this answers is not in the document]
Comment (upsj) [reply core/preconditioner/isai.cpp:216]: I chose this to avoid the alternative `std::shared_ptr<Csr>(static_cast<...*>(this->get_approximate_inverse()->transpose.release()))`, yes. I personally don't expect a few additional dynamic_casts in core code to have any noticeable runtime impact, especially since they don't need to traverse the type hierarchy in any way, just change the static type.

So the answer to your questions would be: no, it's not necessary, but IMO it makes for much nicer code.

File: core/preconditioner/jacobi.cpp [hunk 22]
```diff
@@ -142,6 +144,46 @@ void Jacobi<ValueType, IndexType>::write(mat_data &data) const
 }
 
 
+template <typename ValueType, typename IndexType>
+std::unique_ptr<LinOp> Jacobi<ValueType, IndexType>::transpose() const
+{
+    auto res = std::unique_ptr<Jacobi<ValueType, IndexType>>(
+        new Jacobi<ValueType, IndexType>(this->get_executor()));
+    res->set_size(this->get_size());
```
[the remark this answers is not in the document]
Comment (upsj) [reply core/preconditioner/jacobi.cpp:152]: Good point, I didn't really consider rectangular matrices.

File: reference/test/solver/upper_trs_kernels.cpp (hunk 19 above)
Comment (upsj) [reply reference/test/solver/upper_trs_kernels.cpp:232]: Yes, I guess it makes sense to tag #534 here

File: core/preconditioner/jacobi.cpp (hunk 22 above)
[the remark this answers is not in the document]
Comment (upsj) [reply core/preconditioner/jacobi.cpp:152]: Now I remember the reason: The Jacobi generation already throws an exception with rectangular matrices. So I'll add a comment explaining the reason for not using `transpose` here.

https://github.com/ginkgo-project/ginkgo/blob/4ac2b437ebae5237747d59a9237bb85913984072/core/preconditioner/jacobi.cpp#L162
https://github.com/ginkgo-project/ginkgo/blob/4ac2b437ebae5237747d59a9237bb85913984072/core/preconditioner/jacobi.cpp#L163

File: cuda/test/preconditioner/jacobi_kernels.cpp (hunk 10 above)
Comment (upsj) [reply cuda/test/preconditioner/jacobi_kernels.cpp:334]: The tests are already incredibly fast (< 50ms each as far as I remember), so I wouldn't worry about it.
