### PR TITLE
Fix warnings.

### LINKED ISSUE #174: Reducing the amount of warnings
This is a summary of the discussion which rose during PR #168. This is a mix of @gflegar's contributions and mine.

There are currently a lot of warnings generated when compiling Ginkgo with the flags `-Wall -Wextra -pedantic`. Most of them are part of two categories, either unused arguments or an extra `;` mostly due to putting a `;` after a macro call which doesn't end in a typical statement.

Here is a summary with GCC 8.2.0
```bash
$ make clean
$ make 2> warnings                                     # without CUDA
$ cat warnings | grep -e "\[-[Wp]" | wc -l       # try to get only the [-W or [-p header for warnings
  25447
$ cat warnings | grep "unused-parameter" | wc -l
  15226
$ cat warnings | grep "extra ‘;’" | wc -l
  9301
# Note that over 900 warnings are not part of either of those
```

### The extra ';' warnings
`;` is defined as a null statement, and as such can appear anywhere where a statement can and should be ignored by the compiler. The problem with macros is that they can either define a complete statement (as in `#define F f() {}`), or just a prefix which has to be followed by a statement or used in an expression `#define F f()`. Using the former without a semicolon can cause confusion as it is not clear if code like `F G` means that `G` is used to complete the definition generated by `F`, or if they are two separate macros. On the other hand, always following a macro with a semicolon (even when it is not needed) clarifies this: `F; G;` are two separate statement and `F G;` signifies that `F` modifies the definition of `G`.

The question is what is more important: making clear the meaning of the macro, or making sure there are no false-positive compiler warnings.

One option could be to declare a function after macros that define a full statement. The following code compiles without warnings with both `clang++ -Wall -Wextra -pedantic -std=c++11` and `g++ -Wall -Wextra -pedantic -std=c++11`:

```c++
#define F void f() {} void __gko_macro_terminator__()
#define G void g() {} void __gko_macro_terminator__()
#define S struct S { int x; } s; void __gko_macro_terminator__()

S;
F;
G;

int main() {
    f();
    auto gx = s.x;
    S;
    auto lx = (s.x = 0);
    return gx + lx;
}
```

Note that for some of the current macros this would also mean polluting some of the class's public methods space.

### PR DESCRIPTION
**Pull request by pratikvn**
This pull request tries to fix some warnings that can be fixed mentioned in #174 . The different warnings and the solutions adopted for each are mentioned below:

+ [x] `warning: extra ; ignored` : False positive `;` warnings.
     Solution:~~(FIX) 1. To be fixed with adding an function that defines a full statement (example above).~~
           ~~(IGNORE) 2. Ones for which a full statement cannot be used due to overloading problems.~~
(FIX) By adding `static_assert(true, "message")` statements
+ [x] `warning: inheriting constructors must be inherited from a direct base class`
    Solution: (IGNORE): As it is only used for mixins.
+ [x] `warning: ISO C++11 requires at least one argument for the "..." in a variadic macro`
    Solution: ~~(IGNORE). Supposed to be [fixed](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0306r4.html) in C++2a~~
                       (FIX) by adding an additional macro that takes in `_kernel` as a parameter. 
+ [x] `warning: unused parameters [-Wunused-parameters]` 
    Solution: (FIX) 1. The ones actually unused in the function.
                   (IGNORE) 2. False positives:
                                 - The ones that are a part of variadic macros.
                                 - The ones that are a part of variadic templates and arguments.
                                 - The ones that appear due to the `NOT_IMPLEMENTED` declaration.
                                 - The ones intentionally left unused to have a uniform interface.
+ [x] `warning: comparison between signed and unsigned integers ` 
    Solution: (FIX)1. Some of the wrong types.
                   (IGNORE) 2. to prefer `auto` over explicit setting in loops.
+ [x] `warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]  ` 
    Solution: (IGNORE) 1. warnings showed mainly for `reinterpret_cast`, but this seems to actually allowed in the [standard, 5.2.10/11](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3242.pdf) and I think it is intended in Ginkgo especially for std::complex casts for the GPU and for adaptive precision support. 
+ [x] `warning: foo_ will be initialized after bar_ [-Wreorder] ` 
    Solution: (FIX) Change the ordering in the initialization or the declaration.

FIX: Implies that any code satisfying this condition should be fixed.
IGNORE: Implies either that the warning is a false-positive, is an error of the compiler or is an actual intended behaviour that the compiler interprets as a warning.

The current number of warnings are:
````
$ cat warnings | grep -e "\[-[Wp]" | wc -l 
15531

$ cat warnings | grep "inheriting constructors" | wc -l
4

$ cat warnings | grep "-Wunused-parameter" | wc -l
14109

$ cat warnings | grep "-Wstrict-aliasing" | wc -l
39

$ cat warnings | grep "warning: ISO C++11 requires at least one argument" | wc -l
1164

````

Most of the remaining warnings are the `unused parameter` warnings, which seem to be for the variadic macros and for variadic templates which the compiler does not seem to identify properly and hence I think these can be ignored.

Fixes #174 

Updated numbers:
Now, it can be run with `-pedantic-error`

````
$ cat warnings | grep -e "\[-[Wp]" | wc -l 
570

$ cat warnings | grep "inheriting constructors" | wc -l
2

$ cat warnings | grep "-Wunused-parameter" | wc -l
411

$ cat warnings | grep "-Wstrict-aliasing" | wc -l
0

$ cat warnings | grep "warning: ISO C++11 requires at least one argument" | wc -l
0
````

### CODE REVIEW

**Comment by tcojean** [comment]
>    * Solution: Ignore for now. Supposed to be [fixed](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0306r4.html) in C++2a

Which ones are doing this, do you know? Is there really no way to fix this, by adding some dummy parameter or whatever? In general, what warnings can mean (particularly GCC's `pedantic`) is that they could very well be a bug.

Note that there is also a possibility to disable warnings for some piece of code for both clang and gcc: 
https://stackoverflow.com/questions/35587137/how-to-suppress-gcc-variadic-macro-argument-warning-for-zero-arguments-for-a-par

**Comment by tcojean** [comment]
In summary, the best case would be that we can compile Ginkgo with `-pedantic-errors -Werror=pedantic`.

File: cuda/base/cublas_bindings.hpp [hunk 1]
```diff
@@ -90,7 +90,8 @@ struct is_supported<std::complex<double>> : std::true_type {};
             CublasName(handle, transa, transb, m, n, k, as_culibs_type(alpha), \
                        as_culibs_type(a), lda, as_culibs_type(b), ldb,         \
                        as_culibs_type(beta), as_culibs_type(c), ldc));         \
-    }
+    }                                                                          \
+    void __gko_macro_terminator__()
```
Comment (thoasm) [inline cuda/base/cublas_bindings.hpp]: Any reason you are not using:
```suggestion
    static_assert(true, "")
```
This would not add a dummy function to every class you use the macro while still needing the semicolon at the end.

Also, all names with double underscore are reserved according to the [C++ standard](http://www.lcdf.org/c%2B%2B/clause17.html#s17.4.3.1), so the name has to change:
> Certain sets of names and function signatures are always reserved to the implementation: 
> * Each name that contains a double underscore (_ _) or begins with an underscore followed by an upper case letter (2.11) is reserved to the implementation for any use.

For a more detailed overview, see stackoverflow answer: https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

Comment (pratikvn) [reply cuda/base/cublas_bindings.hpp]: Yeah, that does look better. I thought the `__gko_macro_terminator__()` shows its intent better. Using the `static_assert` seemed like the statement would be out of place. But maybe static assert is applicable to all situations and will not have overload problems as for the function. Thanks!

Comment (thoasm) [reply cuda/base/cublas_bindings.hpp]: In that case, what about:
```c++
static_assert(true, "This assert is only used to enforce a semicolon after the macro call.")
```
or similar. You can write in the message whatever you want, therefore, it is a nice place for a comment.

**Comment by pratikvn** [comment]
@tcojean, I saw that the `ISO C++ 11 ...` warnings are mainly for the variadic macros such as [`GKO_ENABLE_FOR_ALL_EXECUTORS`](https://github.com/ginkgo-project/ginkgo/blob/88fc0306bfff68cc98bd439d307d3e5eb3a1cee5/include/ginkgo/core/base/types.hpp#L388) and for [`GKO_REGISTER_OPERATION`](https://github.com/ginkgo-project/ginkgo/blob/88fc0306bfff68cc98bd439d307d3e5eb3a1cee5/include/ginkgo/core/base/executor.hpp#L263) which uses the `GKO_ENABLE_FOR_ALL_EXECUTORS` macro. I will fix it with the `#pragma GCC system_header` inclusion. Thanks.

File: cuda/base/cublas_bindings.hpp (hunk 1 above)
Comment (pratikvn) [reply cuda/base/cublas_bindings.hpp]: That works. Thanks!

**Comment by tcojean** [comment]
@pratikvn you could also consider making a specific version of the macro which takes the `_kernel` parameter on top of it, and have one without it. This would create a (very small) code duplication, but would keep out hundreds if not thousands of warning...

The `#pragma GCC` does not really fix the problem, it only tells GCC to shut up about it.

**Comment by pratikvn** [comment]
This should be ready for a re-review again. It should be possible to run this with the `-pedantic-errors` now. What is the preferred method of doing this in modern cmake ?

**Comment by tcojean** [comment]
According to various presentations, summarized here [[1]], adding flags to treat warnings as error is not very smart. I think the best thing we could do is to add a flag to ensure the compilers always show pedantic warnings, and ourselves ensure that we remove these warnings from time to time.

In general, we could maybe add the flag `-Wpedantic` to all Ginkgo targets by using `target_compile_options` [[2]]. I guess we can make the flag public if we add it?


[1]: https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#warnings-and-errors
[2]: https://cmake.org/cmake/help/v3.9/command/target_compile_options.html

**Comment by thoasm** [comment]
I would like this to be part of our normal build process, but I would not directly use `-Wpedantic` as some platforms use different options for that (especially Visual Studio, which uses completely different flags, see [this documentation](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=vs-2017)).
Can we make this a variable that we set differently (in the root CMakeFile) depending on the makefiles we generate?

**Comment by gflegar** [comment]
> In general, we could maybe add the flag `-Wpedantic` to all Ginkgo targets by using `target_compile_options` [[2](https://cmake.org/cmake/help/v3.9/command/target_compile_options.html)]. I guess we can make the flag public if we add it?

We should use [`add_compile_options`](https://cmake.org/cmake/help/v3.14/command/add_compile_options.html) for that, [according to Mathieu Ropert](https://youtu.be/eC9-iRN2b04?t=1480). There's also an example how to handle MSVC in his talk.

**Comment by gflegar** [comment]
> @pratikvn you could also consider making a specific version of the macro which takes the `_kernel` parameter on top of it, and have one without it. This would create a (very small) code duplication, but would keep out hundreds if not thousands of warning...

I would go this way. The current state is in fact a bug, and not a false-positive. Whether or not we think of it as an omission in the standard, and major compilers support it, we should aim at C++11 compatibility whenever possible to make it more likely Ginkgo works on non-standard compilers. C++20 is not even out yet, and I don't think we'll be able to use it before 2025 anyway, which is a long time from now.

Btw: maybe it may be useful to consider bumping the standard version to C++14 after Ginkgo 1.0.0 is out? It is 5 years old now, so maybe compiler support for its features is good enough to start using it...

**Comment by gflegar** [comment]
> I guess we can make the flag public if we add it?

Just a note: [NO](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#dont-abuse-usage-requirements) :smile:

**Comment by tcojean** [comment]
> We should use [`add_compile_options`](https://cmake.org/cmake/help/v3.14/command/add_compile_options.html) for that, [according to Mathieu Ropert](https://youtu.be/eC9-iRN2b04?t=1480). There's also an example how to handle MSVC in his talk. (And also in the documentation of `add_compile_options`).

The problem with that is that makes it global and is used for any subdirectory, right? In that case, we may not want to go with this global one, because there could be a risk of specifying this flag for our dependencies. I cannot say we want/can fix the problems in our dependencies, keeping that to Ginkgo seems to be the best for me.

>> I guess we can make the flag public if we add it?

> Just a note: [NO](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#dont-abuse-usage-requirements) 😄

Your are completely right. We should use PRIVATE for this. Thanks for the note.

File: include/ginkgo/core/base/types.hpp [hunk 2]
```diff
@@ -371,6 +371,22 @@ GKO_ATTRIBUTES constexpr bool operator!=(precision_reduction x,
...
+ *
+ * -   the first one is replaced with the executor class name
+ * -   the second one with the name of the kernel to be bound
+ *
+ * @param _enable_macro  macro name which will be called
+ * @param _kernel  kernel which will be bound to the operation
+ *
+ * @note  the macro is not called for ReferenceExecutor
+ */
+#define GKO_ENABLE_KERNEL_FOR_ALL_EXECUTORS(_enable_macro, _kernel) \
```
Comment (thoasm) [inline include/ginkgo/core/base/types.hpp]: Did you replace the `GKO_ENABLE_FOR_ALL_EXECUTORS` with this? Or are both currently in use (just saw that you replaced the previous mentioned one with the marked one in the file `include/ginkgo/core/base/executor.hpp`).

Comment (pratikvn) [reply include/ginkgo/core/base/types.hpp]: `GKO_ENABLE_FOR_ALL_EXECUTORS` is still used in `include/ginkgo/core/base/executor.hpp`. So, both are currently in use and hence there is some code duplication.

**Comment by gflegar** [comment]
> The problem with that is that makes it global and is used for any subdirectory, right? In that case, we may not want to go with this global one, because there could be a risk of specifying this flag for our dependencies. I cannot say we want/can fix the problems in our dependencies, keeping that to Ginkgo seems to be the best for me.

We could specify it per module (core, reference, omp, cuda) to avoid this problem.

File: core/CMakeLists.txt [hunk 3]
```diff
@@ -38,6 +38,7 @@ endif()
 
 ginkgo_compile_features(ginkgo)
 
+target_compile_options(ginkgo PRIVATE "-Wpedantic")
```
Comment (thoasm) [inline core/CMakeLists.txt]: I am not a fan of adding this `-Wpedantic` directly here. I would prefer a varialbe or something similar to be defined in the root CMake file, where it can be set depending on the used compiler and altered in a single place for every part of ginkgo (e.g. if we decide we want to add `-Wconversion` or similar).

Comment (pratikvn) [reply core/CMakeLists.txt]: Yeah, that is better. Do you think it is better to create three separate variables `GINKGO_CORE_WARNING_FLAGS`, `GKO_REFERENCE_WARNING_FLAGS` and similar or one variable `GINKGO_WARNING_FLAGS` would be better ?

Comment (thoasm) [reply core/CMakeLists.txt]: I don't think we should call them `WARNING_FLAGS`, but instead `COMPILE_FLAGS`, as we might add some non-warning related flags. For now, a single variable could be enough, although I have no idea how they are forwarded in the CUDA case (if they are forwarded to both nvcc and host compiler, or just to one of them)...

**Comment by tcojean** [comment]
Pratik, after trying a bit I saw that we do not need the `#pragma GCC` thing to get pedantic compilation without errors. I also saw there was some problems left with the the semicolon fixes so I changed some of that. The following link is a patch which contains the changes.
https://pastebin.com/k0eZhuS0

Overall, with the changes I made and after rebasing the PR and checking no new problems were recently added, this should be able to be merged.

If you feel like it, you could also add a new CI stage containing a build step which compiles Ginkgo with `-pedantic-errors -Werror=pedantic` and allow the stage to fail. This could serve as a way to check if some PR break pendantic compatibility and allow us to fix these problems from time to time. We could also add other warning checks later as needed.

**Comment by pratikvn** [comment]
Ah, for some reason, my compiler did not complain about these semi-colons. 

I actually left in the `#pragma GCC` in `executor.hpp` and `lin_op.hpp` because there are some variadic macros, which I am not sure how to fix for example, the `GKO_FORWARD_DECLARE` and the `GKO_FACTORY_PARAMETER`. The `#pragma GCC` made sure these were ignored. Anyway, these warnings somehow dont seem to show up as errors when compiled with the `-Werror=pedantic` flags. So, technically, maybe they are fine ?

**Comment by tcojean** [comment]
>I actually left in the `#pragma GCC` in `executor.hpp` and `lin_op.hpp` because there are some variadic macros

I would definitely remove that. I would consider it if it was required for some impossible to fix pedantic compatibility, but that is not the case, we do not need it. I would rather not hide warnings in general (otherwise we cannot fix them, nor can we fix new added warnings to those files), so please remove it.

**Comment by pratikvn** [comment]
@tcojean, I tried to add a job with warnings as an error but ran into problems on the CI. Please feel free to `push --force` and fix this. Thanks,

**Comment by tcojean** [comment]
@pratikvn I should have fixed your problem with the previous commits.

See the [relevant pipeline](https://gitlab.com/ginkgo-project/ginkgo-public-ci/pipelines/49777263).

File: cuda/base/cusparse_bindings.hpp [hunk 4]
```diff
@@ -160,15 +166,15 @@ GKO_BIND_CUSPARSE_TRANSPOSE64(ValueType, detail::not_implemented);
...
+        cusparseIndexBase_t idxBase) GKO_NOT_IMPLEMENTED
 
 #define GKO_BIND_CUSPARSE_CONJ_TRANSPOSE64(ValueType, CusparseName)          \
     inline void conj_transpose(                                              \
         cusparseHandle_t handle, size_type m, size_type n, size_type nnz,    \
         const ValueType *OrigValA, const int64 *OrigRowPtrA,                 \
         const int64 *OrigColIndA, ValueType *TransValA, int64 *TransRowPtrA, \
         int64 *TransColIndA, cusparseAction_t copyValues,                    \
-        cusparseIndexBase_t idxBase) GKO_NOT_IMPLEMENTED;
+        cusparseIndexBase_t idxBase) GKO_NOT_IMPLEMENTED
```
Comment (thoasm) [inline cuda/base/cusparse_bindings.hpp]: Do we need to remove the semicolons after `GKO_NOT_IMPLEMENTED` after you also added the `static_asserts` there?

Comment (tcojean) [reply cuda/base/cusparse_bindings.hpp]: Good point, in fact they should be required.

File: cuda/base/cusparse_bindings.hpp [hunk 5]
```diff
@@ -166,15 +172,21 @@ GKO_BIND_CUSPARSE_TRANSPOSE64(ValueType, detail::not_implemented);
...
     inline void conj_transpose(                                              \
         cusparseHandle_t handle, size_type m, size_type n, size_type nnz,    \
         const ValueType *OrigValA, const int64 *OrigRowPtrA,                 \
         const int64 *OrigColIndA, ValueType *TransValA, int64 *TransRowPtrA, \
         int64 *TransColIndA, cusparseAction_t copyValues,                    \
-        cusparseIndexBase_t idxBase) GKO_NOT_IMPLEMENTED
+        cusparseIndexBase_t idxBase) GKO_NOT_IMPLEMENTED;                    \
+    static_assert(true,                                                      \
+                  "This assert is used to counter the false positive extra " \
+                  "semi-colon warnings")
```
Comment (thoasm) [inline cuda/base/cusparse_bindings.hpp]: You don't need these `asserts` because you already have them in `GKO_NOT_IMPLEMENTED`.
Just the semicolons after `GKO_NOT_IMPLEMENTED` should be fine.

Comment (pratikvn) [reply cuda/base/cusparse_bindings.hpp]: Yep, sorry..

Comment (pratikvn) [reply cuda/base/cusparse_bindings.hpp]: Sorry, it is actually needed, because that is a macro in itself and is used later.

Comment (thoasm) [reply cuda/base/cusparse_bindings.hpp]: In that case, it should be as it was before (without the assert and without the semicolon).
Sorry for the confusion.

Comment (pratikvn) [reply cuda/base/cusparse_bindings.hpp]: I think the way it is now is also fine, because ideally, you would like to replace the `GKO_NOT_IMPLEMENTED ` with an implementation and then you would need the asserts.

Comment (thoasm) [reply cuda/base/cusparse_bindings.hpp]: That is true.

**Comment by pratikvn** [comment]
> @pratikvn I should have fixed your problem with the previous commits.
> See the relevant pipeline.

Thanks for this @tcojean . There are still a few warnings regarding the variadic macros, but I think they are a bit more difficult to resolve, so maybe we can leave them for now. But if anyone has any ideas, I am happy to fix them.
