### PR TITLE
Fix FindNVTX, thrust::identity<T>, and cuFFT removed error in cuda 13

### LINKED ISSUE #1925: FindNVTX fails with CUDA 13
The `FindNVTX` module finds the path using `find_path` with a hint:

https://github.com/ginkgo-project/ginkgo/blob/95253ebcd0bd8c972529fc2669d6bccc5eeda271/cmake/Modules/FindNVTX.cmake#L30-L34

However, `CUDAToolkit_INCLUDE_DIRS` is a list which has 2 items since CUDA 13 whereas previously it had probably just 1 item. Hence, the module is checking these paths (on Arch Linux):

    /opt/cuda/targets/x86_64-linux/include/nvToolsExt.h
    /opt/cuda/targets/x86_64-linux/include/cccl/nvtx3/nvToolsExt.h

And it misses the correct path `/opt/cuda/targets/x86_64-linux/include/nvtx3/nvToolsExt.h`

### PR DESCRIPTION
**Pull request by yhmtsai**
This PR fixes #1925, which mentioned building issue in cuda 13.

Three issues:
- FindNVTX: in some platforms, `CUDAToolkit_INCLUDE_DIRS` might contain more than one. `${list}/suffix` only adds suffix to the last one, which leads the `find_path` failed.
- `thrust::identity<T>`: it is removed in cuda 13. They provide `::cuda::std::identity` now. Note. it does not contain conversion like `thrust::identity<T>` reference: https://nvidia.github.io/cccl/cccl/3.0_migration_guide.html
- cuFFT removed error: cuFFT in cuda removes three error type (`CUFFT_INCOMPLETE_PARAMETER_LIST`, `CUFFT_PARSE_ERROR`, `CUFFT_LICENSE_ERROR`) reference: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cufft-release-13-0

close #1925

### CODE REVIEW

File: common/cuda_hip/factorization/factorization_kernels.cpp [hunk 1]
```diff
@@ -588,12 +588,23 @@ void symbolic_validate(
             factors_lookup.storage.get_const_data(), found.get_data(),
             missing.get_data());
     }
+    auto get_bool_identity = []() {
```
Comment (MarcelKoch) [inline common/cuda_hip/factorization/factorization_kernels.cpp:591]: should we perhaps just implement https://en.cppreference.com/w/cpp/utility/functional/identity.html in our `std_extension.hpp` until we can use the c++20 version? Then we don't need to check for the cuda version.

**Review by MarcelKoch — CHANGES_REQUESTED** [review]

File: common/cuda_hip/factorization/factorization_kernels.cpp (hunk 1 above)
Comment (yhmtsai) [reply common/cuda_hip/factorization/factorization_kernels.cpp:591]: I may still go for this now when we only use it here.
I have seen their code has `__is_identity` and used in somewhere. It might be useful when they can skip this to avoid another layer code and help the compiler optimization.
std::identity will be not in this case
