### PR TITLE
Cuda11 support

### LINKED ISSUE #613: [JOSS REVIEW] Use of deprecated function `cusparseScsrmv ` in CUDA executor
This issue is part of the functionality aspect of a JOSS review (see #597 )

I have run into a new issue in building CUDA-enabled ginkgo while building.  After a successful `cmake`, an attempt to build with `make` gives
```
[  1%] Building CXX object cuda/CMakeFiles/ginkgo_cuda.dir/base/executor.cpp.o
In file included from /home/ajacobs/Reporoot/ginkgo/cuda/base/executor.cpp:43:
/home/ajacobs/Reporoot/ginkgo/cuda/base/cusparse_bindings.hpp: In function ‘void gko::kernels::cuda::cusparse::spmv(cusparseHandle_t, cusparseOperation_t, gko::int32, gko::int32, gko::int32, const float*, cusparseMatDescr_t, const float*, const int32*, const int32*, const float*, const float*, float*)’:
/home/ajacobs/Reporoot/ginkgo/cuda/base/cusparse_bindings.hpp:118:33: error: ‘cusparseScsrmv’ was not declared in this scope; did you mean ‘cusparseSbsrmv’?
  118 | GKO_BIND_CUSPARSE32_SPMV(float, cusparseScsrmv);
``` 

I deploy the latest stable CUDA tookit and dev environment, so when I looked at my cusparse header files I confirmed that `cusparseScsrmv` is no longer provided and was deprecated as mentioned [here (section 8.8.)](https://docs.nvidia.com/cuda/archive/10.1/pdf/CUSPARSE_Library.pdf).

NVIDIA suggests "use cusparseCsrmvEx() instead."

In the meantime, I will explore workarounds (and welcome suggestions).  As CUDA toolkits are made current, however, this will become an issue for more users/systems.

### PR DESCRIPTION
**Pull request by yhmtsai**
this PR add cuda11 support.

Summary:
1. add generic spmv/spmm into cusparse spmv/spmm
2. use cusp_coo/cusp_csr as cusp_gcoo/cusp_gcsr in benchmark/spmv 
3. use correct architecture flag in cuda/test
4. use cuda11's cooperative group because it support complex shuffle, but we remove the parent type in `tiled_partition`
5. add cuda 10.2/11 gitlab ci (linux) and cuda11 github action (windows)
6. replace deprecated spgemm2 and gthr by new cusparse generic interface.

Fixes #613

### CODE REVIEW

File: cuda/base/cusparse_bindings.hpp [hunk 1]
```diff
@@ -629,6 +704,49 @@ inline void destroy(csrgemm2Info_t info)
 }
 
 
+#if defined(CUDA_VERSION) && (CUDA_VERSION >= 11000)
+
+
+inline cusparseDnVecDescr_t create_dnvec(int64_t size, void *values,
```
Comment (upsj) [inline cuda/base/cusparse_bindings.hpp:710]: Suggestion: How about replacing void* values by a template parameter and inferring `valueType = cuda_data_type<ValueType>`? Same for create_csr

File: cuda/matrix/csr_kernels.cu [hunk 2]
```diff
@@ -307,23 +307,56 @@ void spmv(std::shared_ptr<const CudaExecutor> exec,
...
+
+                cusparse::destroy(descr);
+#else  // CUDA_VERSION >= 11000
+                cusparseOperation_t trans = CUSPARSE_OPERATION_NON_TRANSPOSE;
+                cusparseSpMVAlg_t alg = CUSPARSE_CSRMV_ALG1;
+                auto row_ptrs =
+                    const_cast<IndexType *>(a->get_const_row_ptrs());
+                auto col_idxs =
+                    const_cast<IndexType *>(a->get_const_col_idxs());
+                auto values = const_cast<ValueType *>(a->get_const_values());
```
Comment (tcojean) [inline cuda/matrix/csr_kernels.cu:336]: Any idea why they take non const? That's a bit weird, do they want to change these somehow?

File: cuda/matrix/csr_kernels.cu [hunk 3]
```diff
@@ -895,7 +1105,31 @@ void conj_transpose(std::shared_ptr<const CudaExecutor> exec,
...
             orig->get_const_values(), orig->get_const_row_ptrs(),
             orig->get_const_col_idxs(), trans->get_values(),
-            trans->get_col_idxs(), trans->get_row_ptrs(), copyValues, idxBase);
+            trans->get_row_ptrs(), trans->get_col_idxs(), copyValues, idxBase);
+#else  // CUDA_VERSION >= 11000
+        cudaDataType_t cu_value =
+            gko::kernels::cuda::cuda_data_type<ValueType>();
+        cusparseAction_t copyValues = CUSPARSE_ACTION_NUMERIC;
+        cusparseIndexBase_t idxBase = CUSPARSE_INDEX_BASE_ZERO;
+        cusparseCsr2CscAlg_t alg = CUSPARSE_CSR2CSC_ALG2;
```
Comment (upsj) [inline cuda/matrix/csr_kernels.cu:1114]: Important: We should always keep this at ALG1, since ALG2 doesn't guarantee any ordering of the columns. This could silently break a lot of algorithms! Can you maybe add a test for Csr::transpose (if we don't already have one) that tests that `is_sorted_by_column_index()` is true?
```suggestion
        cusparseCsr2CscAlg_t alg = CUSPARSE_CSR2CSC_ALG1;
```

File: cuda/matrix/csr_kernels.cu (hunk 2 above)
Comment (upsj) [reply cuda/matrix/csr_kernels.cu:336]: They don't care about const correctness and want to allow themselves to reorder the columns if necessary, I would guess.

File: cuda/base/cusparse_bindings.hpp [hunk 4]
```diff
@@ -226,6 +265,8 @@ GKO_BIND_CUSPARSE64_SPMM(ValueType, detail::not_implemented);
 #undef GKO_BIND_CUSPARSE32_SPMM
 #undef GKO_BIND_CUSPARSE64_SPMM
 
+#endif
```
[the remark this answers is not in the document]
Comment (yhmtsai) [reply cuda/base/cusparse_bindings.hpp:268]: We currently put the function which does similar thing together.
It needs many `#if`-block but easily identify which function has different version.
Another way is to create a global `#if` to handle these function.
It can reduce the number of `#if`-block but maybe gives very complicated structure.
For example, we need to handle several version of benchmark/spmv.
1. old coo/csr/ell/hybrid is available in 9 ~ 10.2
2. generic coo/csr/csr is available after 10.2 in non-Windows or 11 in all platform.
3. coo/csr is alias for gcoo/gcsr after 11

[the remark this answers is not in the document]
Comment (tcojean) [reply cuda/base/cusparse_bindings.hpp:268]: I mean, the previous one in this case has the same definition I think, so it wouldn't hurt to simply merge it with the one above. You do not have to change the file structure.

[the remark this answers is not in the document]
Comment (yhmtsai) [reply cuda/base/cusparse_bindings.hpp:268]: I see

File: .gitlab-ci.yml [hunk 5]
```diff
@@ -397,6 +397,126 @@ build/clang-cuda101/clang/cuda/debug/static:
...
+    BUILD_TYPE: "Debug"
+    BUILD_SHARED_LIBS: "OFF"
+    CUDA_ARCH: 35
+  only:
+    variables:
+      - $RUN_CI_TAG
+  tags:
+    - private_ci
+    - cuda
+    - gpu
```
[the remark this answers is not in the document]
Comment (yhmtsai) [reply .gitlab-ci.yml]: I remove the cuda 10.1 corresponding one because cuda 10.1 has additional clang-cuda test.

File: cuda/base/cusparse_bindings.hpp [hunk 6]
```diff
@@ -504,101 +623,119 @@ GKO_BIND_CUSPARSE64_CSR2HYB(ValueType, detail::not_implemented);
...
+        const ValueType *OrigValA, const int32 *OrigRowPtrA,                  \
+        const int32 *OrigColIndA, ValueType *TransValA, int32 *TransRowPtrA,  \
+        int32 *TransColIndA, cusparseAction_t copyValues,                     \
+        cusparseIndexBase_t idxBase)                                          \
     {                                                                         \
         GKO_ASSERT_NO_CUSPARSE_ERRORS(                                        \
             CusparseName(handle, m, n, nnz, as_culibs_type(OrigValA),         \
                          OrigRowPtrA, OrigColIndA, as_culibs_type(TransValA), \
-                         TransRowPtrA, TransColIndA, copyValues, idxBase));   \
+                         TransColIndA, TransRowPtrA, copyValues, idxBase));   \
```
Comment (pratikvn) [inline cuda/base/cusparse_bindings.hpp:657]: Why did this change ?

File: cuda/base/cusparse_handle.hpp [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+
+namespace gko {
+namespace kernels {
+namespace cuda {
+/**
+ * @brief The CUSPARSE namespace.
+ *
+ * @ingroup cusparse
+ */
+namespace cusparse {
```
Comment (pratikvn) [inline cuda/base/cusparse_handle.hpp:52]: Is there any specific reason you do this for cusparse and not for cublas ?

**Comment by yhmtsai** [comment]
I also add the comments on `#endif` when the block only contains `#if-#endif`.
```c
#if condition
#endif // condition
```

File: cuda/matrix/csr_kernels.cu [hunk 8]
```diff
@@ -868,7 +1053,31 @@ void transpose(std::shared_ptr<const CudaExecutor> exec,
             orig->get_size()[1], orig->get_num_stored_elements(),
             orig->get_const_values(), orig->get_const_row_ptrs(),
             orig->get_const_col_idxs(), trans->get_values(),
-            trans->get_col_idxs(), trans->get_row_ptrs(), copyValues, idxBase);
+            trans->get_row_ptrs(), trans->get_col_idxs(), copyValues, idxBase);
```
Comment (yhmtsai) [inline cuda/matrix/csr_kernels.cu:1056]: I also change the ordering here

File: cuda/base/cusparse_bindings.hpp (hunk 6 above)
Comment (yhmtsai) [reply cuda/base/cusparse_bindings.hpp:657]: cusparseCsr2csc uses csc by (CscVal, CscRowInd, CscColPtr) - (1)
cusparseCsr2cscEx2 uses csc by (CscVal, CscColPtr, CscRowInd) - (2)
We use it mainly for transposing, so I think using transposed_csr by (transVal, transRowPtr, transColInd), i.e. (2),should be much familiar and not confusing.

File: cuda/base/cusparse_handle.hpp (hunk 7 above)
Comment (yhmtsai) [reply cuda/base/cusparse_handle.hpp:52]: maybe @upsj could answer it?

Comment (upsj) [reply cuda/base/cusparse_handle.hpp:52]: Yes, cusparse_bindings.hpp doesn't compile on plain C++ compilers because the NVCC version macros are not defined. So I had to separate these parts.

Comment (pratikvn) [reply cuda/base/cusparse_handle.hpp:52]: For uniformity, we could do the same for cublas as well ?

Comment (upsj) [reply cuda/base/cusparse_handle.hpp:52]: I don't think that's necessary (yet), since the interfaces are always the same.

File: cuda/matrix/csr_kernels.cu [hunk 9]
```diff
@@ -385,6 +417,34 @@ void advanced_spmv(std::shared_ptr<const CudaExecutor> exec,
...
+            auto mat = cusparse::create_csr(a->get_size()[0], a->get_size()[1],
+                                            a->get_num_stored_elements(),
+                                            row_ptrs, col_idxs, values);
+            auto b_val = const_cast<ValueType *>(b->get_const_values());
+            auto c_val = c->get_values();
+            auto vecb =
+                cusparse::create_dnvec(b->get_num_stored_elements(), b_val);
+            auto vecc =
+                cusparse::create_dnvec(c->get_num_stored_elements(), c_val);
+            size_t buffer_size = 0;
```
Comment (thoasm) [inline cuda/matrix/csr_kernels.cu:435]: nit: Please either use `std::size_t` or `size_type`.
```suggestion
            std::size_t buffer_size = 0;
```

File: cuda/base/cusparse_handle.hpp (hunk 7 above)
Comment (pratikvn) [reply cuda/base/cusparse_handle.hpp:52]: Ok

File: cuda/base/cusparse_bindings.hpp (hunk 6 above)
Comment (yhmtsai) [reply cuda/base/cusparse_bindings.hpp:657]: also another point is original we use transRowPtr as ColInd, which is wrong.
