### PR TITLE
Fix the (cuda|hip)DeviceReset issue.

### LINKED ISSUE #461: CUDA executor always calls `cudaDeviceReset()` when destroyed
Currently, the CUDA executor always calls `cudaDeviceReset()` ([documentation for `cudaDeviceReset()`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1gef69dd5c6d0206c2b8d099abac61f217)) when it is destroyed (and the last executor on that device). This is done in [cuda/base/executor.cpp](https://github.com/ginkgo-project/ginkgo/blob/develop/cuda/base/executor.cpp#L67). The problem is that this call frees all allocated memory, including everything that was done by other libraries or the user itself.

We first need to investigate why we need this call to begin with. It is likely that we need it for `cuda-memcheck` for [Leak Checking](https://docs.nvidia.com/cuda/cuda-memcheck/index.html#leak-checking), but it is possible that it is not the only reason why it is there.

For multi-GPU, we might actually have to use a combination of [cudaGetDevice(int)](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g80861db2ce7c29b6e8055af8ae01bc78) and [`cudaSetDevice(int)`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g159587909ffa0791bbe4b40187a4c6bb) to reset the correct GPU.

This issue was found by @nbeams

### PR DESCRIPTION
**Pull request by tcojean**
To fix this problem, an optional boolean class is added which controls
whether to reset or not the device controlled by the executor. By 
default, the device is not reset.

All examples, benchmarks and the last executors from the tests are
modified to pass the correct value to reset the device after use. This
ensures that our CI tools and users can keep tracking memory leaks
internally.

Fixes #461

### CODE REVIEW

File: include/ginkgo/core/base/executor.hpp [hunk 1]
```diff
@@ -783,6 +783,39 @@ class ExecutorBase : public Executor {
...
+ * Controls whether the DeviceReset function should be called thanks to a
+ * boolean.
+ */
+class EnableDeviceReset {
+public:
+    /**
+     * Toggles the Device Reset capability. If it was previously true, set
+     * false, and vice versa.
+     */
+    void toggle_device_reset() { device_reset_ = !device_reset_; }
```
Comment (upsj) [inline include/ginkgo/core/base/executor.hpp:796]: In my opinion, setting and getting are more common use cases than toggling and getting.

File: include/ginkgo/core/base/executor.hpp [hunk 2]
```diff
@@ -783,6 +783,40 @@ class ExecutorBase : public Executor {
 };
 
 
+/**
+ * Controls whether the DeviceReset function should be called thanks to a
+ * boolean.
```
Comment (yhmtsai) [inline include/ginkgo/core/base/executor.hpp:788]: Could you add some comments about the reset only considered in the last destroyed executor (device_id)?
If some executor with reset on but some with reset off, the resetting call only depends on the last one.
Also, no matter how users set these executors, ginkgo does not call reset when some executors (under ginkgo) are alive.

Comment (tcojean) [reply include/ginkgo/core/base/executor.hpp:788]: Good point.

**Comment by tcojean** [comment]
@yhmtsai I think changing the behavior is fine in this case since it's a fix (in most cases, resetting is more trouble than it's worth). It does break binary compatibility also since we now have an extra optional parameter. I don't think we can do much about this.

**Comment by yhmtsai** [comment]
@tcojean thanks for explanation.
