### PR TITLE
Some fixes for compiling with the `-D_GLIBCXX_DEBUG` flag.

### LINKED ISSUE #1143: libstdc++ assertion failures in debug mode
While working on an [AUR package](https://github.com/ginkgo-project/ginkgo/discussions/1095), I've got this error:

```
[8/555] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
FAILED: _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
/usr/bin/c++ -DGTEST_CREATE_SHARED_LIBRARY=1 -Dgtest_EXPORTS -I/home/klinkovsky/build/builddir/ginkgo-hpc-git/src/build/_deps/googletest-src/googletest/include -I/home/klinkovsky/build/builddir/ginkgo-hpc-git/src/build/_deps/googletest-src/googletest -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -fPIC -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=0 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -MD -MT _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -MF _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o.d -o _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -c /home/klinkovsky/build/builddir/ginkgo-hpc-git/src/build/_deps/googletest-src/googletest/src/gtest-all.cc
In file included from /usr/include/c++/12.2.0/ios:40,
                 from /usr/include/c++/12.2.0/ostream:38,
                 from /home/klinkovsky/build/builddir/ginkgo-hpc-git/src/build/_deps/googletest-src/googletest/include/gtest/gtest.h:58,
                 from /home/klinkovsky/build/builddir/ginkgo-hpc-git/src/build/_deps/googletest-src/googletest/src/gtest-all.cc:38:
In static member function ‘static std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)’,
    inlined from ‘static void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.0/bits/basic_string.h:423:21,
    inlined from ‘std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.0/bits/basic_string.tcc:532:22,
    inlined from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.0/bits/basic_string.h:2171:19,
    inlined from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::insert(size_type, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12.2.0/bits/basic_string.h:1928:22,
    inlined from ‘std::__cxx11::basic_string<_CharT, _Traits, _Allocator> std::operator+(const _CharT*, __cxx11::basic_string<_CharT, _Traits, _Allocator>&&) [with _CharT = char; _Traits = char_traits<char>; _Alloc = allocator<char>]’ at /usr/include/c++/12.2.0/bits/basic_string.h:3541:36,
    inlined from ‘static std::string testing::internal::StreamingListener::UrlEncode(const char*)’ at /home/klinkovsky/build/builddir/ginkgo-hpc-git/src/build/_deps/googletest-src/googletest/src/gtest.cc:4882:27:
/usr/include/c++/12.2.0/bits/char_traits.h:431:56: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

This is with external gtest downloaded by ginkgo. When I use the system gtest-1.12.1-1 on Arch Linux, the error is gone, but some of the tests fail at runtime due to weird assertion errors in the stdlib:
```
  1/273 Test  #85: omp/test/reorder/rcm_kernels .............................Subprocess aborted***Exception:   4.77 sec
Running main() from /build/gtest/src/googletest-release-1.12.1/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Rcm
[ RUN      ] Rcm.OmpPermutationIsRcmOrdered
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = int; _Alloc = gko::ExecutorAllocator<int>; reference = int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

        Start 233: test/matrix/matrix_cuda
  2/273 Test #232: test/matrix/matrix_omp ...................................Subprocess aborted***Exception:   4.82 sec
Running main() from /build/gtest/src/googletest-release-1.12.1/googletest/src/gtest_main.cc
[==========] Running 323 tests from 17 test suites.
[----------] Global test environment set-up.
[----------] 19 tests from Matrix/DenseWithDefaultStride, where TypeParam = DenseWithDefaultStride
[ RUN      ] Matrix/DenseWithDefaultStride.SpMVIsEquivalentToRef
/usr/include/c++/12.2.0/bits/uniform_int_dist.h:97: std::uniform_int_distribution<_IntType>::param_type::param_type(_IntType, _IntType) [with _IntType = long int]: Assertion '_M_a <= _M_b' failed.

        Start 213: test/factorization/par_ilut_kernels_cuda
  3/273 Test #210: test/factorization/par_ilu_kernels_omp ...................Subprocess aborted***Exception:   4.88 sec
Running main() from /build/gtest/src/googletest-release-1.12.1/googletest/src/gtest_main.cc
[==========] Running 56 tests from 8 test suites.
[----------] Global test environment set-up.
[----------] 7 tests from ParIlu/<float, int>, where TypeParam = std::tuple<float, int>
[ RUN      ] ParIlu/<float, int>.KernelAddDiagonalElementsSortedEquivalentToRef
[       OK ] ParIlu/<float, int>.KernelAddDiagonalElementsSortedEquivalentToRef (73 ms)
[ RUN      ] ParIlu/<float, int>.KernelAddDiagonalElementsUnsortedEquivalentToRef
/usr/include/c++/12.2.0/bits/uniform_int_dist.h:97: std::uniform_int_distribution<_IntType>::param_type::param_type(_IntType, _IntType) [with _IntType = int]: Assertion '_M_a <= _M_b' failed.

        Start 203: test/factorization/lu_kernels_cuda
  4/273 Test #211: test/factorization/par_ilu_kernels_cuda ..................Subprocess aborted***Exception:   9.61 sec
Running main() from /build/gtest/src/googletest-release-1.12.1/googletest/src/gtest_main.cc
[==========] Running 56 tests from 8 test suites.
[----------] Global test environment set-up.
[----------] 7 tests from ParIlu/<float, int>, where TypeParam = std::tuple<float, int>
[ RUN      ] ParIlu/<float, int>.KernelAddDiagonalElementsSortedEquivalentToRef
[       OK ] ParIlu/<float, int>.KernelAddDiagonalElementsSortedEquivalentToRef (717 ms)
[ RUN      ] ParIlu/<float, int>.KernelAddDiagonalElementsUnsortedEquivalentToRef
/usr/include/c++/12.2.0/bits/uniform_int_dist.h:97: std::uniform_int_distribution<_IntType>::param_type::param_type(_IntType, _IntType) [with _IntType = int]: Assertion '_M_a <= _M_b' failed.

        Start 209: test/factorization/par_ict_kernels_cuda
  5/273 Test #233: test/matrix/matrix_cuda ..................................Subprocess aborted***Exception:   9.19 sec
Running main() from /build/gtest/src/googletest-release-1.12.1/googletest/src/gtest_main.cc
[==========] Running 399 tests from 21 test suites.
[----------] Global test environment set-up.
[----------] 19 tests from Matrix/DenseWithDefaultStride, where TypeParam = DenseWithDefaultStride
[ RUN      ] Matrix/DenseWithDefaultStride.SpMVIsEquivalentToRef
/usr/include/c++/12.2.0/bits/uniform_int_dist.h:97: std::uniform_int_distribution<_IntType>::param_type::param_type(_IntType, _IntType) [with _IntType = long int]: Assertion '_M_a <= _M_b' failed.
```

### PR DESCRIPTION
**Pull request by pratikvn**
This PR adds some recommended fixes needed to compile by adding the `-D_GLIBCXX_DEBUG` flag to all the source files. More details about the flag and its purpose [can be found here](https://gcc.gnu.org/onlinedocs/libstdc%2B%2B/manual/debug_mode_using.html)

Some issues:

1. It seems like this significantly increases the runtime of some of the tests (due to the explicit bound checks ?).
2. When using stdlib containers in device code, workarounds are needed, for example in accessors.

Not sure if we want to have this for 1.5.0.

Fixes #1143

### CODE REVIEW

File: accessor/accessor_helper.hpp [hunk 1]
```diff
@@ -78,13 +78,16 @@ struct row_major_helper_s {
         const std::array<SizeType, (total_dim > 1 ? total_dim - 1 : 0)>& stride,
         IndexType first, Indices&&... idxs)
     {
+        auto size_access = reinterpret_cast<const SizeType*>(&size);
```
Comment (thoasm) [inline accessor/accessor_helper.hpp:81]: These `reinterpret_cast`s are not great...
Why don't you simply use `size.data()`? This is the safer approach as it is (to my knowledge) not guaranteed that `reinterpret_cast` works fine with `array`s.
Also, why is this necessary? `std::array` has been around for quite a while, so it should work. Additionally, making the accesses less safe / less readable and potentially remove optimizations just for one debug builds seems unreasonable.

**Review by thoasm — CHANGES_REQUESTED** [review]
I dislike the `reinterpret_cast` on `std:;array`s and it must be addressed before I change my review.
We also need to discuss where we set the compiler options. I am fine with your approach, but there could be a reason why we opted for our own compiler flags.

File: CMakeLists.txt [hunk 2]
```diff
@@ -115,6 +115,8 @@ endif()
 if(MINGW OR CYGWIN)
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wa,-mbig-obj")
 endif()
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GINKGO_COMPILER_FLAGS}")
+set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} ${GINKGO_CUDA_COMPILER_FLAGS}")
```
[the remark this answers is not in the document]
Comment (upsj) [reply CMakeLists.txt:119]: I think honestly the reason is limited familiarity with CMake's scoping rules, as everything GINKGO_COMPILER_FLAGS does can also be handled by setting CMAKE_CXX_FLAGS only for the subdirectory that Ginkgo is being built in.

**Comment by pratikvn** [comment]
LGTM too. Feel free to merge when you are ready.

**Comment by upsj** [comment]
We had three small bugs that need to be fixed, and I'll try to reduce the test runtime, but otherwise it's ready, yes

**Review by upsj — APPROVED** [review]

File: test/factorization/par_ilu_kernels.cpp [hunk 3]
```diff
@@ -78,6 +78,11 @@ class ParIlu : public CommonTestFixture {
             const auto row_start = row_ptrs[row];
             const auto row_end = row_ptrs[row + 1];
             const int num_row_elements = row_end - row_start;
+            if (num_row_elements == 0) {
+                // nothing to do if the row is empty (avoid UB in the following
+                // initialization of idx_dist)
+                continue;
```
Comment (yhmtsai) [inline test/factorization/par_ilu_kernels.cpp:84]: I do not get it. creating and destroying something but not using is UB?

Comment (upsj) [reply test/factorization/par_ilu_kernels.cpp:84]: std::uniform_int_distribution requires end >= start, otherwise e.g. if the computations used a division internally, they might divide by zero, which crashes the program

File: test/factorization/par_ilu_kernels.cpp [hunk 4]
```diff
@@ -78,6 +78,11 @@ class ParIlu : public CommonTestFixture {
             const auto row_start = row_ptrs[row];
             const auto row_end = row_ptrs[row + 1];
             const int num_row_elements = row_end - row_start;
+            if (num_row_elements == 0) {
```
Comment (lahwaacz) [inline test/factorization/par_ilu_kernels.cpp:81]: Btw. why do you have `int row` and `int num_row_elements` here while the input arguments are `index_type`?

Comment (upsj) [reply test/factorization/par_ilu_kernels.cpp:81]: no particular reason beyond that nobody brought it up during review ;)
