### PR TITLE
Some fixes for Scalar Jacobi.

### LINKED ISSUE #838: Scalar Jacobi specialization incomplete
With the Scalar Jacobi specialization, there are a few places that need to be adapted as well:
* `write` uses block_ptrs, which are empty in scalar Jacobi, so we probably need to special-case this and ignore precision reduction
* `(conj_)transpose` needs to directly copy over the block values instead of calling the transpose_jacobi kernel
* `convert_to(Dense)` has the same issues as `write`.

### PR DESCRIPTION
**Pull request by pratikvn**
This PR aims to fix some of the incomplete functionalities that were left during the specialization for Scalar Jacobi.

Fixes #838

### CODE REVIEW

File: common/preconditioner/jacobi_kernels.hpp.inc [hunk 1]
```diff
@@ -231,11 +231,35 @@ __global__ __launch_bounds__(default_block_size) void scalar_apply(
...
+
+template <typename ValueType>
+__global__ __launch_bounds__(default_block_size) void conj_diagonal(
+    size_type num_elems, const ValueType *__restrict__ diag,
+    ValueType *__restrict__ conj_diag)
+{
+    const auto tidx = thread::get_thread_id_flat();
+
+    if (tidx < num_elems) {
+        conj_diag[tidx] = gko::conj(diag[tidx]);
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.hpp.inc:249]:
```suggestion
        conj_diag[tidx] = conj(diag[tidx]);
```

File: core/preconditioner/jacobi.cpp [hunk 2]
```diff
@@ -141,29 +150,44 @@ void Jacobi<ValueType, IndexType>::write(mat_data &data) const
...
-        GKO_PRECONDITIONER_JACOBI_RESOLVE_PRECISION(ValueType, prec, {
-            const auto block_data =
-                reinterpret_cast<const resolved_precision *>(group_data) +
-                scheme.get_block_offset(block);
-            for (IndexType row = 0; row < block_size; ++row) {
-                for (IndexType col = 0; col < block_size; ++col) {
+    if (parameters_.max_block_size == 1) {
+        for (IndexType row = 0; row < data.size[0]; ++row) {
+            for (IndexType col = 0; col < data.size[1]; ++col) {
+                if (row == col) {
```
Comment (upsj) [inline core/preconditioner/jacobi.cpp:156]:
```suggestion
            auto col = row;
```

File: omp/preconditioner/jacobi_kernels.cpp [hunk 3]
```diff
@@ -696,6 +696,56 @@ GKO_INSTANTIATE_FOR_EACH_VALUE_AND_INDEX_TYPE(
...
+    GKO_DECLARE_JACOBI_SCALAR_CONVERT_TO_DENSE_KERNEL);
+
+
+template <typename ValueType>
+void scalar_conj(std::shared_ptr<const DefaultExecutor> exec,
+                 const Array<ValueType> &diag, Array<ValueType> &conj_diag)
+{
+#pragma omp parallel for
+    for (size_type i = 0; i < diag.get_num_elems(); ++i) {
+        conj_diag.get_data()[i] = gko::conj(diag.get_const_data()[i]);
```
Comment (upsj) [inline omp/preconditioner/jacobi_kernels.cpp:728]:
```suggestion
        conj_diag.get_data()[i] = conj(diag.get_const_data()[i]);
```

**Review by upsj — APPROVED** [review]
LGTM, just a few nits! If you want, you can also use common kernels for conj_diag, inv_diag and convert_to_dense.

File: common/preconditioner/jacobi_kernels.cpp [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+
+template <typename ValueType>
+void invert_diagonal(std::shared_ptr<const DefaultExecutor> exec,
+                     const Array<ValueType> &diag, Array<ValueType> &inv_diag)
+{
+    auto one_val = one<ValueType>();
+    run_kernel(
+        exec,
+        [] GKO_KERNEL(auto elem, auto diag, auto inv_diag, auto one_val) {
+            inv_diag[elem] = one_val / diag[elem];
```
Comment (yhmtsai) [inline common/preconditioner/jacobi_kernels.cpp:76]: original apply will use one when the diag is zero.
which one should we use here?

File: reference/preconditioner/jacobi_kernels.cpp [hunk 5]
```diff
@@ -602,6 +596,31 @@ GKO_INSTANTIATE_FOR_EACH_VALUE_TYPE(
...
+GKO_INSTANTIATE_FOR_EACH_VALUE_TYPE(GKO_DECLARE_JACOBI_SCALAR_CONJ_KERNEL);
+
+
+template <typename ValueType>
+void invert_diagonal(std::shared_ptr<const DefaultExecutor> exec,
+                     const Array<ValueType> &diag, Array<ValueType> &inv_diag)
+{
+    for (size_type i = 0; i < diag.get_num_elems(); ++i) {
+        inv_diag.get_data()[i] =
+            static_cast<ValueType>(1.0) / diag.get_const_data()[i];
```
Comment (yhmtsai) [inline reference/preconditioner/jacobi_kernels.cpp:617]: same comment

File: reference/preconditioner/jacobi_kernels.cpp [hunk 6]
```diff
@@ -674,6 +693,28 @@ GKO_INSTANTIATE_FOR_EACH_VALUE_AND_INDEX_TYPE(
     GKO_DECLARE_JACOBI_CONJ_TRANSPOSE_KERNEL);
 
 
+template <typename ValueType>
+void scalar_convert_to_dense(std::shared_ptr<const DefaultExecutor> exec,
+                             const Array<ValueType> &blocks,
+                             ValueType *result_values,
+                             const gko::dim<2> &matrix_size,
+                             size_type result_stride)
```
Comment (yhmtsai) [inline reference/preconditioner/jacobi_kernels.cpp:701]: can get these variable by passing result dense?

File: reference/test/preconditioner/jacobi.cpp [hunk 7]
```diff
@@ -310,6 +310,94 @@ TYPED_TEST(Jacobi, CanBeClearedWithAdaptivePrecision)
...
+
+    auto dense_j = gko::matrix::Dense<value_type>::create(this->exec);
+    dense_j->copy_from(scalar_j.get());
+    auto j_val = scalar_j->get_blocks();
+
+    EXPECT_EQ(dense_j->at(0, 0), j_val[0]);
+    EXPECT_EQ(dense_j->at(1, 1), j_val[1]);
+    EXPECT_EQ(dense_j->at(2, 2), j_val[2]);
+    EXPECT_EQ(dense_j->at(3, 3), j_val[3]);
+    EXPECT_EQ(dense_j->at(4, 4), j_val[4]);
```
Comment (yhmtsai) [inline reference/test/preconditioner/jacobi.cpp:332]: also need to check others are zero?

File: common/preconditioner/jacobi_kernels.cpp [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+template <typename ValueType>
+void scalar_conj(std::shared_ptr<const DefaultExecutor> exec,
+                 const Array<ValueType> &diag, Array<ValueType> &conj_diag)
+{
+    run_kernel(
+        exec,
+        [] GKO_KERNEL(auto elem, auto diag, auto conj_diag) {
+            conj_diag[elem] = conj(diag[elem]);
+        },
+        diag.get_num_elems(), diag.get_const_data(), conj_diag.get_data());
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:62]: nit: We have mappings for Array -> pointer and Dense -> accessor
```suggestion
        diag.get_num_elems(), diag, conj_diag);
```

File: reference/test/preconditioner/jacobi.cpp [hunk 9]
```diff
@@ -310,6 +310,94 @@ TYPED_TEST(Jacobi, CanBeClearedWithAdaptivePrecision)
...
+}
+
+
+template <typename T>
+void init_array(T *arr, std::initializer_list<T> vals)
+{
+    for (auto elem : vals) {
+        *(arr++) = elem;
+    }
+}
```
Comment (yhmtsai) [inline reference/test/preconditioner/jacobi.cpp:366]: can use std::fill_n

File: common/preconditioner/jacobi_kernels.cpp [hunk 10]
```diff
@@ -0,0 +1,163 @@
...
+void invert_diagonal(std::shared_ptr<const DefaultExecutor> exec,
+                     const Array<ValueType> &diag, Array<ValueType> &inv_diag)
+{
+    auto one_val = one<ValueType>();
+    run_kernel(
+        exec,
+        [] GKO_KERNEL(auto elem, auto diag, auto inv_diag, auto one_val) {
+            inv_diag[elem] = one_val / diag[elem];
+        },
+        diag.get_num_elems(), diag.get_const_data(), inv_diag.get_data(),
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:78]:
```suggestion
        diag.get_num_elems(), diag, inv_diag,
```

File: common/preconditioner/jacobi_kernels.cpp (hunk 4 above)
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:76]:
```suggestion
            inv_diag[elem] = one(diag[elem]) / diag[elem];
```

File: common/preconditioner/jacobi_kernels.cpp [hunk 11]
```diff
@@ -0,0 +1,163 @@
...
+{
+    if (alpha->get_size()[1] > 1) {
+        run_kernel(
+            exec,
+            [] GKO_KERNEL(auto row, auto col, auto diag, auto alpha, auto b,
+                          auto beta, auto x) {
+                x(row, col) = beta[col] * x(row, col) +
+                              alpha[col] * b(row, col) * diag[row];
+            },
+            x->get_size(), diag.get_const_data(), alpha->get_const_values(), b,
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:101]:
```suggestion
            x->get_size(), diag, alpha->get_const_values(), b,
```

File: common/preconditioner/jacobi_kernels.cpp [hunk 12]
```diff
@@ -0,0 +1,163 @@
...
+            beta->get_const_values(), x);
+    } else {
+        run_kernel(
+            exec,
+            [] GKO_KERNEL(auto row, auto col, auto diag, auto alpha, auto b,
+                          auto beta, auto x) {
+                x(row, col) =
+                    beta[0] * x(row, col) + alpha[0] * b(row, col) * diag[row];
+            },
+            x->get_size(), diag.get_const_data(), alpha->get_const_values(), b,
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:111]:
```suggestion
            x->get_size(), diag, alpha->get_const_values(), b,
```

File: common/preconditioner/jacobi_kernels.cpp [hunk 13]
```diff
@@ -0,0 +1,163 @@
...
+                         const Array<ValueType> &diag,
+                         const matrix::Dense<ValueType> *b,
+                         matrix::Dense<ValueType> *x)
+{
+    run_kernel(
+        exec,
+        [] GKO_KERNEL(auto row, auto col, auto diag, auto b, auto x) {
+            x(row, col) = b(row, col) * diag[row];
+        },
+        x->get_size(), diag.get_const_data(), b, x);
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:130]:
```suggestion
        x->get_size(), diag, b, x);
```

File: common/preconditioner/jacobi_kernels.cpp [hunk 14]
```diff
@@ -0,0 +1,163 @@
...
+                             const Array<ValueType> &blocks,
+                             ValueType *result_values,
+                             const gko::dim<2> &matrix_size,
+                             size_type result_stride)
+{
+    run_kernel(
+        exec,
+        [] GKO_KERNEL(auto row, auto col, auto stride, auto diag,
+                      auto result_values) {
+            result_values[row * stride + col] = zero<ValueType>();
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:148]:
```suggestion
            result_values[row * stride + col] = zero(diag[row]);
```

File: common/preconditioner/jacobi_kernels.cpp [hunk 15]
```diff
@@ -0,0 +1,163 @@
...
+            if (row == col) {
+                result_values[row * stride + col] = diag[row];
+            }
+        },
+        matrix_size, result_stride, blocks.get_const_data(), result_values);
```
Comment (upsj) [inline common/preconditioner/jacobi_kernels.cpp:153]:
```suggestion
        matrix_size, result_stride, blocks, result_values);
```

File: reference/test/preconditioner/jacobi.cpp [hunk 16]
```diff
@@ -310,6 +310,94 @@ TYPED_TEST(Jacobi, CanBeClearedWithAdaptivePrecision)
...
+
+
+TEST(Jacobi, ScalarJacobiCanBeConjTransposed)
```
Comment (yhmtsai) [inline reference/test/preconditioner/jacobi.cpp:369]: will it be the same testsuite or different in gtest output?

**Review by upsj — COMMENTED** [review]
The code can probably be simplified a bit:

File: reference/test/preconditioner/jacobi.cpp [hunk 17]
```diff
@@ -310,6 +310,94 @@ TYPED_TEST(Jacobi, CanBeClearedWithAdaptivePrecision)
...
+    auto dense_j = gko::matrix::Dense<value_type>::create(this->exec);
+    auto t_j = scalar_j->transpose();
+    auto trans_j = gko::as<Bj>(t_j.get())->get_blocks();
+    auto scal_j = scalar_j->get_blocks();
+
+    EXPECT_EQ(trans_j[0], scal_j[0]);
+    EXPECT_EQ(trans_j[1], scal_j[1]);
+    EXPECT_EQ(trans_j[2], scal_j[2]);
+    EXPECT_EQ(trans_j[3], scal_j[3]);
+    EXPECT_EQ(trans_j[4], scal_j[4]);
```
Comment (yhmtsai) [inline reference/test/preconditioner/jacobi.cpp:356]: also need to check others property like num_blocks. same for conj trans

**Review by yhmtsai — APPROVED** [review]
LGTM but some nit

File: common/preconditioner/jacobi_kernels.cpp (hunk 4 above)
Comment (upsj) [reply common/preconditioner/jacobi_kernels.cpp:76]: You should be able to use safe_divide from math.hpp

File: reference/test/preconditioner/jacobi.cpp (hunk 16 above)
Comment (pratikvn) [reply reference/test/preconditioner/jacobi.cpp:379]: No, it will just be shown in another block.

File: reference/test/preconditioner/jacobi.cpp (hunk 9 above)
Comment (pratikvn) [reply reference/test/preconditioner/jacobi.cpp:376]: No, I am filling different values from the initializer list.

Comment (upsj) [reply reference/test/preconditioner/jacobi.cpp:376]: std::copy then?

Comment (pratikvn) [reply reference/test/preconditioner/jacobi.cpp]: Sure, copy works. I did not think it was necessary as this was simple code anyway. But I have updated it now.

**Review by tcojean — APPROVED** [review]
LGTM

**Comment by tcojean** [comment]
Maybe we should add a few lines in the main `jacobi.hpp` to mention that we also have this version? The current description only mentions (adaptive) block jacobi.
