### PR TITLE
Update and fix the create new algorithm script

### LINKED ISSUE #408: Create new algorithm does not add HIP files
Currently, `create_new_algorithm.sh` does not modify and add the files for the HIP executor. 

+ The `cuda2hip.sh`does creates the new hip files from the cuda files.

### PR DESCRIPTION
**Pull request by tcojean**
This updates the `create_new_algorithm.sh` to HIP and provides new features.

+ Provide HIP support.
+ Allow file definitions in `TEMPLATE_FILES` to match multiple files
  + This allows to properly copy from jacobi which is split into multiple files
	  due to its compiling complexity.
  + This would also allow to have multiple test files for one functionality, and
	  in general make this script a little bit more future proof.
+ Manage the new `#include "common/.../xxx_kernels.hpp.inc"` pattern, by
  removing this line from the newly created files.
+ Improve the `todo_xxx.txt` output file by trying to provide a TODO list.

Closes #408.

### CODE REVIEW

File: dev_tools/scripts/create_new_algorithm.sh [hunk 1]
```diff
@@ -97,11 +97,13 @@ TEMPLATE_FILES=(
     "${name}_kernels.hpp"
     "${name}_kernels.cpp"
     "${name}_kernels.cpp"
-    "${name}_kernels.c*"
+    "${name}_*.[ch]*"
```
Comment (upsj) [inline dev_tools/scripts/create_new_algorithm.sh]: Do we have a common naming scheme for CUDA header files? I see some `.cuh` and some `.hpp` files, so we might not catch all files with this pattern.

File: dev_tools/scripts/create_new_algorithm.sh [hunk 2]
```diff
@@ -146,131 +154,146 @@ TEMPLATE_FILES_DESCRIPTIONS=(
...
 
+            cp ${GINKGO_ROOT_DIR}/$source_path ${TMPDIR}/$destpath
 
-    # Comment all code
-    awk '/^{$/,/^}$/ { if ($0 == "{"){ print "GKO_NOT_IMPLEMENTED;"; print "//" $0; print "// TODO (script): change the code imported from '${source_type}'/'${source_name}' if needed"; next} else { print "//" $0; next }} 1' ${TMPDIR}/$destpath > tmp
-    mv tmp  ${TMPDIR}/$destpath
+            # Replace all instances of source_name by the user's requested name
+            perl -n -i -e "print unless m/.*common.*${source_name}_kernels.hpp.inc.*/" ${TMPDIR}/$destpath
+            perl -pi -e "s/${source_name}/$name/g" ${TMPDIR}/$destpath
+            perl -pi -e "s/${source_name^}/$Name/g" ${TMPDIR}/$destpath
```
Comment (upsj) [inline dev_tools/scripts/create_new_algorithm.sh]: Do we not need `$NAME` any more?

File: dev_tools/scripts/create_new_algorithm.sh [hunk 3]
```diff
@@ -146,131 +154,146 @@ TEMPLATE_FILES_DESCRIPTIONS=(
...
+            echo "Warning: Source file $sourcepath was not found."
         fi
     done
+done
 
-
+if [ $execute == 1 ]
+then
     echo -e "cleaning up temporary files."
     rm -rf ${TMPDIR}
```
Comment (pratikvn) [inline dev_tools/scripts/create_new_algorithm.sh]: On my Mac, this causes problems as if you remove the ${TMPDIR}, then `mktemp` in line 283 does not copy/modify the CMakeLists.txt properly. If I move this removal of the ${TMPDIR} while exiting the if clause, then everything works as expected.

File: dev_tools/scripts/create_new_algorithm.sh (hunk 1 above)
Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: I don't think we really have. I will have to take care of `cuh` down there in the code when I look for `hpp` I guess.

File: dev_tools/scripts/create_new_algorithm.sh (hunk 2 above)
Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: good point, I don't know what happened to that one, I will put it back

File: dev_tools/scripts/create_new_algorithm.sh (hunk 3 above)
Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: Thanks for checking. There is no problem with the `grep` command? Has Mac has different bash tools, I was a bit unsure about this.

**Comment by tcojean** [comment]
@upsj The way HIP is made doesn't allow to create a target then add sources, you need to path the sources into a variable, so indeed we need the special `HIP` treatment sadly.

File: dev_tools/scripts/create_new_algorithm.sh (hunk 3 above)
Comment (pratikvn) [reply dev_tools/scripts/create_new_algorithm.sh]: No, `grep` seems to work fine for me. I have `grep` from BSD which I think has full compatibility with GNU grep.

File: dev_tools/scripts/create_new_algorithm.sh [hunk 4]
```diff
@@ -146,131 +154,146 @@ TEMPLATE_FILES_DESCRIPTIONS=(
...
 
-
     if [ $automatic_additions -eq 1 ]
     then
         ## Try to automatically add the files to CMakeLists
         echo -e "Modifiying CMakeLists.txt and common_kernels.inc.cpp"
```
Comment (pratikvn) [inline dev_tools/scripts/create_new_algorithm.sh]:
```suggestion
        echo -e "Modifying CMakeLists.txt and common_kernels.inc.cpp"
```

File: dev_tools/scripts/create_new_algorithm.sh (hunk 3 above)
Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: Could you try reverting to the default one and check if this works? Or is that the default one?

Comment (pratikvn) [reply dev_tools/scripts/create_new_algorithm.sh]: I think the one I have is the default one you get with Mac.

Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: I don't understand why the `${TMPDIR}` has anything to do with `mktemp`, as they aren't used togother and do `${TMPDIR}` is not made from `mktemp` actually. I put the `rm` at the end, how is it now?

Comment (pratikvn) [reply dev_tools/scripts/create_new_algorithm.sh]: I say the grep works fine because, for example in the `hip/CMakeLists.txt`, the file is added correctly to the `GINKGO_HIP_SOURCES` and the other `CMakeLists.txt` additions are correct as well.

Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: About grep, I also meant the last one which finds automatically generates a list of files with lines of TODO items.

Comment (pratikvn) [reply dev_tools/scripts/create_new_algorithm.sh]: Yes, that seems to be correct as well. I do get a huge list of TODO with line numbers and file names.

File: dev_tools/scripts/create_new_algorithm.sh (hunk 1 above)
Comment (upsj) [reply dev_tools/scripts/create_new_algorithm.sh]: Ah, I was thinking of regular expressions, not globs. So this should be fine

File: dev_tools/scripts/create_new_algorithm.sh (hunk 3 above)
Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: OK thanks for checking

File: dev_tools/scripts/create_new_algorithm.sh [hunk 5]
```diff
@@ -342,38 +366,31 @@ then
...
+    echo "reference/test/${source_type}/CMakeLists.txt"       | tee -a todo_${name}.txt
+    echo ""                                                   | tee -a todo_${name}.txt
+    echo "omp/CMakeLists.txt"                                 | tee -a todo_${name}.txt
+    echo "omp/test/${source_type}/CMakeLists.txt"             | tee -a todo_${name}.txt
+    echo ""                                                   | tee -a todo_${name}.txt
+    echo "cuda/CMakeLists.txt"                                | tee -a todo_${name}.txt
+    echo "cuda/test/${source_type}/CMakeLists.txt"            | tee -a todo_${name}.txt
+    echo ""                                                   | tee -a todo_${name}.txt
+    echo ""                                                   | tee -a todo_${name}.txt
+    echo "The following header file has to modified:"         | tee -a todo_${name}.txt
```
Comment (thoasm) [inline dev_tools/scripts/create_new_algorithm.sh]:
```suggestion
    echo "The following header file has to be modified:"         | tee -a todo_${name}.txt
```

File: dev_tools/scripts/create_new_algorithm.sh [hunk 6]
```diff
@@ -342,38 +366,31 @@ then
...
+    echo "core/test/${source_type}/CMakeLists.txt"            | tee -a todo_${name}.txt
+    echo ""                                                   | tee -a todo_${name}.txt
+    echo "reference/CMakeLists.txt"                           | tee -a todo_${name}.txt
+    echo "reference/test/${source_type}/CMakeLists.txt"       | tee -a todo_${name}.txt
+    echo ""                                                   | tee -a todo_${name}.txt
+    echo "omp/CMakeLists.txt"                                 | tee -a todo_${name}.txt
+    echo "omp/test/${source_type}/CMakeLists.txt"             | tee -a todo_${name}.txt
+    echo ""                                                   | tee -a todo_${name}.txt
+    echo "cuda/CMakeLists.txt"                                | tee -a todo_${name}.txt
+    echo "cuda/test/${source_type}/CMakeLists.txt"            | tee -a todo_${name}.txt
```
Comment (thoasm) [inline dev_tools/scripts/create_new_algorithm.sh]: What about the HIP `CMakeLists.txt`? Should the user also modify it, or is it actually fine?

File: dev_tools/scripts/create_new_algorithm.sh [hunk 7]
```diff
@@ -97,11 +97,13 @@ TEMPLATE_FILES=(
     "${name}_kernels.hpp"
     "${name}_kernels.cpp"
     "${name}_kernels.cpp"
-    "${name}_kernels.c*"
+    "${name}*.[ch]*"
```
Comment (thoasm) [inline dev_tools/scripts/create_new_algorithm.sh]: Is there a reason for that change for the CUDA kernels? If I use `cg2` as the new name and base it on `solver cg`, it creates both `cg2_kernels.cu` and `cg2s_kernels.cu`.
As far as I can tell, this currently only happens with `cg`, since `cgs` has `cg` as a prefix.

File: dev_tools/scripts/create_new_algorithm.sh (hunk 6 above)
Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: Good point, this is taken care of I simply did not update this.

File: dev_tools/scripts/create_new_algorithm.sh (hunk 7 above)
Comment (tcojean) [reply dev_tools/scripts/create_new_algorithm.sh]: Good point. The change is for jacobi though as this has multiple files and all need to be matched (including a header). I will put a `_` there which restrict the sort of names you can give, but indeed removes the bug that you talk about.

Comment (thoasm) [reply dev_tools/scripts/create_new_algorithm.sh]: I think that is fine since the name should not really contain an `_`.
