### PR TITLE
Fix misaligned addresses with batched loggers

### LINKED ISSUE #1576: CUDA error with batched solvers
Using Ginkgo batched solvers I sometimes get the following errors

```bash
terminate called after throwing an instance of 'gko::CudaError'
  what():  /tmp/soft/spack-stage/spack-stage-ginkgo-1.7.0-a6wuqlgaxa2t5vkyzdapmgicl73ujdjd/spack-src/cuda/base/executor.cpp:203: synchronize: cudaErrorMisalignedAddress: misaligned address
Abandon
```
This error appears on Ginkgo 1.7.0 release on a V100 GPU with CUDA 12.2.1.

You can find a minimal reproducer in this repository https://github.com/Geoflow/gko_minreproducer/tree/minimal-reproducer. In my case I got the error with a batch size of 1. Am I doing something wrong ?

cc @Geoflow

### PR DESCRIPTION
**Pull request by pratikvn**
This PR fixes errors with cuda misaligned addresses in the batched loggers when mixing 32 bit and 64 bit types reported in #1576. It adds a setup to allow aliasing workspace pointers with arrays of different types, which is necessary to prevent repeated allocations while preventing misaligned issues.

Fixes #1576

### CODE REVIEW

File: include/ginkgo/core/log/batch_logger.hpp [hunk 1]
```diff
@@ -101,7 +103,7 @@ class BatchConvergence final : public gko::log::Logger {
     using mask_type = gko::log::Logger::mask_type;
 
     void on_batch_solver_completed(
-        const array<int>& iteration_count,
+        const array<int64>& iteration_count,
```
Comment (yhmtsai) [inline include/ginkgo/core/log/batch_logger.hpp:106]: Is it the bug of logger or misused in the kernel?
we can only change the public interface if it is the first case.

Comment (pratikvn) [reply include/ginkgo/core/log/batch_logger.hpp:106]: I think the logger needs to store int64 to be efficient. I think we can right now safely assume that no one derives from the BatchConvergence logger.

**Review by upsj — COMMENTED** [review]
Using 64 bit indices doesn't seem to make any sense for batched problems to me. This looks more like a quick patch than a proper fix. I'll try to prototype an example for how we could improve upon this, I think CUB provides a nice blueprint.

**Comment by pratikvn** [comment]
In this case the maximum number of elements possible is equal to the number of batch items. So, I think it is definitely possible to have more than max(int32) for that. Additionally, this is not a shared memory issue, but an issue of using a workspace and storing pointers to different types within the workspace that was causing the misaligned accesses.

Nevertheless, your suggestion on the CUB approach is a nice way to do it, and I will look into that.

**Comment by upsj** [comment]
This change only deals with final iteration counts, which is where IMO 64 bit integers make no sense.

**Comment by pratikvn** [comment]
Yes, only the final iteration counts are being logged, but the number of entries scales with the number of batch items that are being solved, which can possibly more than `max(int32)`

**Comment by upsj** [comment]
The type you use to index an array is independent of the value type of the array, I am talking about the value type

**Comment by pratikvn** [comment]
Ah, yes. I misunderstood your comment. I am looking into the CUB blueprint. That should be usable for correct aligntment of  both the workspace vectors and for the shared memory objects.

**Comment by MarcelKoch** [comment]
I think the PR description and title need to change now.

**Comment by pratikvn** [comment]
I think both the title and description are still valid. I have updated the description now.

File: include/ginkgo/core/solver/batch_solver_base.hpp [hunk 2]
```diff
@@ -289,8 +289,9 @@ class EnableBatchSolver
             auto id = Identity::create(exec, system_matrix->get_size());
             preconditioner_ = std::move(id);
         }
-        const size_type workspace_size = system_matrix->get_num_batch_items() *
-                                         (sizeof(real_type) + sizeof(int));
+        const size_type workspace_size =
+            system_matrix->get_num_batch_items() * 32;
+        // 2 * (sizeof(real_type) + sizeof(int));
```
Comment (MarcelKoch) [inline include/ginkgo/core/solver/batch_solver_base.hpp:294]: So `32 == 2 * (sizeof(real_type) + sizeof(int))`? But that is wrong, `2 * (sizeof(real_type) + sizeof(int)) <= 24`

File: include/ginkgo/core/log/batch_logger.hpp [hunk 3]
```diff
@@ -33,12 +34,11 @@ namespace detail {
 template <typename ValueType>
 struct log_data final {
     using real_type = remove_complex<ValueType>;
+    using idx_type = int;
 
     log_data(std::shared_ptr<const Executor> exec, size_type num_batch_items)
```
Comment (MarcelKoch) [inline include/ginkgo/core/log/batch_logger.hpp:39]: all of this implementation can be moved to core. Then we don't need the CUB file in our public header.

File: include/ginkgo/core/base/types.hpp [hunk 4]
```diff
@@ -35,6 +35,22 @@
...
+// Macros for handling different device error return types uniformly
+#if defined(__CUDACC__)
+#define GKO_DEVICE_ERROR_TYPE cudaError_t
+#define GKO_DEVICE_ERROR_INVALID cudaErrorInvalidValue
+#define GKO_DEVICE_NO_ERROR cudaSuccess
+#elif defined(__HIPCC__)
+#define GKO_DEVICE_ERROR_TYPE hipError_t
+#define GKO_DEVICE_ERROR_INVALID hipErrorInvalidValue
+#define GKO_DEVICE_NO_ERROR hipSuccess
+#else
```
Comment (MarcelKoch) [inline include/ginkgo/core/base/types.hpp:47]: Since only succeess/failure is needed, you don't need these wrappers.

File: include/ginkgo/core/log/batch_logger.hpp [hunk 5]
```diff
@@ -51,17 +51,22 @@ struct log_data final {
...
         if (num_batch_items > 0 && !workspace.is_owning() &&
             workspace.get_size() >= workspace_size) {
+            gko::detail::layout<2> workspace_alias;
+            auto slot_1 = workspace_alias.get_slot(0);
+            auto slot_2 = workspace_alias.get_slot(1);
+            auto iter_alias = slot_1->create_alias<idx_type>(num_batch_items);
+            auto res_alias = slot_2->create_alias<real_type>(num_batch_items);
+
+            // Temporary storage mapping
+            workspace_alias.map_to_buffer(workspace.get_data(), workspace_size);
```
Comment (MarcelKoch) [inline include/ginkgo/core/log/batch_logger.hpp:65]: return code is ignored.

File: core/log/batch_logger.cpp [hunk 6]
```diff
@@ -13,6 +13,53 @@
 namespace gko {
 namespace batch {
 namespace log {
+// namespace detail {
```
Comment (MarcelKoch) [inline core/log/batch_logger.cpp:16]: what's going on with this?

**Review by MarcelKoch — DISMISSED** [review]
Can we maybe first summarize the issue? If I understand it correctly, the issue was the `res_norm` pointer in `batch_logger.hpp`. The alignment of that pointer depends on how many batch items there are, and the size in bytes of the `iter_counts`, which are using the workspace memory before the `res_norm`. In some cases (`num_batch_items==1`) this could lead to an alignment for `res_norm` less than 8 bytes.

The workspace manager from CUB fixes the alignment by ensuring that each memory region from the work space is aligned to at least 8 bytes.

TBH, the CUB implementation seems a bit overkill for us. We just need a function that like
```
T* next_aligned(void* ptr)
```
which gives you a pointer to the next aligned (to 8 bytes I guess) memory location. 

If the CUB implementation should stay, it needs a lot more documentation. I'm also not a fan of the chain `layout->slot->alias`, it could be `layout->alias` directly.

File: core/log/batch_logger.cpp (hunk 6 above)
Comment (MarcelKoch) [reply core/log/batch_logger.cpp:16]: maybe the header was missing some `inline`? Still it should be moved into the core.

File: include/ginkgo/core/base/workspace_aliases.hpp [hunk 7]
```diff
@@ -0,0 +1,252 @@
+// SPDX-FileCopyrightText: 2017 - 2024 The Ginkgo authors
+//
+// SPDX-License-Identifier: BSD-3-Clause
```
[the remark this answers is not in the document]
Comment (pratikvn) [reply include/ginkgo/core/base/workspace_aliases.hpp:3]: It seems the formatter does not let me do that.

File: include/ginkgo/core/log/batch_logger.hpp [hunk 8]
```diff
@@ -51,17 +51,22 @@ struct log_data final {
              array<unsigned char>& workspace)
         : res_norms(exec), iter_counts(exec)
     {
-        const size_type workspace_size =
-            num_batch_items * (sizeof(real_type) + sizeof(int));
+        const size_type workspace_size = num_batch_items * 32;
```
[the remark this answers is not in the document]
Comment (pratikvn) [reply include/ginkgo/core/log/batch_logger.hpp]: No, we just want to ensure enough of a large workspace. In this case, we align everything to 8 bytes.

File: include/ginkgo/core/solver/batch_solver_base.hpp (hunk 2 above)
Comment (pratikvn) [reply include/ginkgo/core/solver/batch_solver_base.hpp]: This comment was wrong. Should be fixed now. But we want to align to 8 bytes, size of `double` to ensure there is no misaligned accesses, which may happen when using the workspace for storing both 4 bytes and 8 bytes (int and double) respectively.

File: include/ginkgo/core/log/batch_logger.hpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (upsj) [reply include/ginkgo/core/log/batch_logger.hpp]: I will take a look at this PR on Wednesday, but I can already tell you that `thrust::complex<double>` needs an alignment of 16 bytes

File: include/ginkgo/core/base/workspace_aliases.hpp
[the remark this answers is not in the document]
Comment (pratikvn) [reply include/ginkgo/core/base/workspace_aliases.hpp:1]: This is needed in the batch logger header, which is needed for the batch solver base classes which cannot be moved to core.

File: include/ginkgo/core/log/batch_logger.hpp (hunk 3 above)
Comment (pratikvn) [reply include/ginkgo/core/log/batch_logger.hpp:39]: Unfortunately, I dont think this can be moved to core.

File: include/ginkgo/core/base/types.hpp (hunk 4 above)
Comment (pratikvn) [reply include/ginkgo/core/base/types.hpp:47]: The plan is to use these for aliasing the shared memory pointers in the device kernels as well. In those cases, we would need the return code which would be useful in narrowing the issue.

File: include/ginkgo/core/log/batch_logger.hpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (pratikvn) [reply include/ginkgo/core/log/batch_logger.hpp]: In this case, we are aligning to the max real floating type, (should be of `remove_complex<T>`), which is 8. But for the general case, yes, I guess we would need to align to 16.

File: include/ginkgo/core/base/workspace_aliases.hpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (MarcelKoch) [reply include/ginkgo/core/base/workspace_aliases.hpp:3]: This is because of our stupid `format_header.sh` script. Maybe format it correctly with reuse, and then commit it with `-n`.

File: core/base/workspace_aliases.hpp [hunk 9]
```diff
@@ -0,0 +1,255 @@
+// SPDX-FileCopyrightText: 2017 - 2024 The Ginkgo authors
+//
+// SPDX-License-Identifier: BSD-3-Clause
```
Comment (MarcelKoch) [inline core/base/workspace_aliases.hpp:3]: I really think this should be different. You can add this file to the exludes in the pre-commit config for the format-headers hook. Then the changes to it won't get overwritten anymore.

File: core/base/workspace_aliases.hpp [hunk 10]
```diff
@@ -0,0 +1,255 @@
...
+class alias;
+
+template <int num_slots, int align_bytes>
+class layout;
+
+/**
+ * Represents a slot of memory which can be aliased. See @alias and @layout on
+ * how this can be used.
+ */
+class slot {
```
Comment (MarcelKoch) [inline core/base/workspace_aliases.hpp:77]: still no idea why there is both `slot` and `alias`. `alias` alone should be enough. But I won't hold anything up over the implementations in this file.

File: include/ginkgo/core/log/batch_logger.hpp [hunk 11]
```diff
@@ -33,39 +33,12 @@ namespace detail {
 template <typename ValueType>
 struct log_data final {
     using real_type = remove_complex<ValueType>;
+    using idx_type = int;
```
Comment (MarcelKoch) [inline include/ginkgo/core/log/batch_logger.hpp:36]: I wouldn't mind
```suggestion
    using index_type = int;
```
I think that would be more consistent with our naming scheme.

File: include/ginkgo/core/solver/batch_solver_base.hpp [hunk 12]
```diff
@@ -289,8 +289,8 @@ class EnableBatchSolver
             auto id = Identity::create(exec, system_matrix->get_size());
             preconditioner_ = std::move(id);
         }
-        const size_type workspace_size = system_matrix->get_num_batch_items() *
-                                         (sizeof(real_type) + sizeof(int));
+        const size_type workspace_size =
+            system_matrix->get_num_batch_items() * 32;
```
Comment (MarcelKoch) [inline include/ginkgo/core/solver/batch_solver_base.hpp:293]: still not entirely sure about where the 32 comes from, but not a blocker.

File: .pre-commit-config.yaml [hunk 13]
```diff
@@ -23,6 +23,7 @@ repos:
         third_party/SuiteSparse/AMD/.*|
         third_party/identify_stream_usage/.*|
         examples/external-lib-interfacing/external-lib-interfacing.cpp
+        core/base/workspace_aliases.hpp
```
Comment (MarcelKoch) [inline .pre-commit-config.yaml:26]: why is the header excluded here? I thought it would not change the copyright from previous years.

File: .pre-commit-config.yaml [hunk 14]
```diff
@@ -35,6 +36,7 @@ repos:
           third_party/SuiteSparse/AMD/.*|
           third_party/identify_stream_usage/.*|
           include/ginkgo/ginkgo.hpp
+          core/base/workspace_aliases.hpp
```
Comment (MarcelKoch) [inline .pre-commit-config.yaml:39]: I think it has to be
```suggestion
        examples/external-lib-interfacing/external-lib-interfacing.cpp|
        core/base/workspace_aliases.hpp
```

File: core/log/batch_logger.cpp [hunk 15]
```diff
@@ -10,9 +10,66 @@
...
+        gko::detail::layout<2, 8> workspace_alias;
+        auto slot_1 = workspace_alias.get_slot(0);
+        auto slot_2 = workspace_alias.get_slot(1);
+        auto iter_alias = slot_1->create_alias<index_type>(num_batch_items);
+        auto res_alias = slot_2->create_alias<real_type>(num_batch_items);
+
+        // Temporary storage mapping
+        auto err = workspace_alias.map_to_buffer(workspace.get_data(),
+                                                 reqd_workspace_size);
+        GKO_ASSERT(err == 0);
```
Comment (MarcelKoch) [inline core/log/batch_logger.cpp:55]:
```suggestion
        GKO_ASSERT(err == GKO_DEVICE_NO_ERROR);
```

File: include/ginkgo/core/base/types.hpp (hunk 4 above)
Comment (MarcelKoch) [reply include/ginkgo/core/base/types.hpp:47]: btw, does this have to be in a public header? Wouldn't a core header be sufficient?

File: .pre-commit-config.yaml (hunk 14 above)
Comment (MarcelKoch) [reply .pre-commit-config.yaml:39]: that should also fix the CI.

**Review by MarcelKoch — CHANGES_REQUESTED** [review]

**Comment by pratikvn** [comment]
the check-format will fail because it uses develop instead of the updated precommit file

File: include/ginkgo/core/base/types.hpp (hunk 4 above)
Comment (yhmtsai) [reply include/ginkgo/core/base/types.hpp:47]: have the same question as MarcelKoch. the current usage only require these alias in the core header not public.

File: core/base/workspace_aliases.hpp [hunk 16]
```diff
@@ -0,0 +1,272 @@
...
+#define GKO_DEVICE_NO_ERROR hipSuccess
+#else
+#define GKO_DEVICE_ERROR_TYPE int
+#define GKO_DEVICE_ERROR_INVALID 1
+#define GKO_DEVICE_NO_ERROR 0
+#endif
+
+
+// This code is a modified version of the code from CCCL
+// (https://github.com/NVIDIA/cccl) (cub/detail/temporary_storage.cuh and
```
Comment (yhmtsai) [inline core/base/workspace_aliases.hpp:31]: maybe also mention what the modified part?
I guess only namespace, error code

File: include/ginkgo/core/log/batch_logger.hpp [hunk 17]
```diff
@@ -33,39 +33,12 @@ namespace detail {
...
-            num_batch_items * (sizeof(real_type) + sizeof(int));
-        if (num_batch_items > 0 && !workspace.is_owning() &&
-            workspace.get_size() >= workspace_size) {
-            iter_counts =
-                array<int>::view(exec, num_batch_items,
-                                 reinterpret_cast<int*>(workspace.get_data()));
-            res_norms = array<real_type>::view(
-                exec, num_batch_items,
-                reinterpret_cast<real_type*>(workspace.get_data() +
-                                             (sizeof(int) * num_batch_items)));
```
Comment (yhmtsai) [inline include/ginkgo/core/log/batch_logger.hpp:64]: originally, I thought it should be solved by using the view on the larger type first.

File: core/log/batch_logger.cpp [hunk 18]
```diff
@@ -10,9 +10,66 @@
...
+}
+
+
+template <typename ValueType>
+log_data<ValueType>::log_data(std::shared_ptr<const Executor> exec,
+                              size_type num_batch_items,
+                              array<unsigned char>& workspace)
+    : res_norms(exec), iter_counts(exec)
+{
+    const size_type reqd_workspace_size = num_batch_items * 32;
```
Comment (yhmtsai) [inline core/log/batch_logger.cpp:42]: If I understand it correctly, the mapping is to ensure the memory address is divisible by the size of data type.
It's also why I think it was enough by viewing the larger data type first.
Assume the workspace data is not aliased from the beginning, which should not be the case if the workspace is the alone allocation, and then the actual memory will need a little more than reqd_workspace_size by cutting the first unaligned part. If the reqd_workspace_size is the same as the workspace allocation, it does not help when the workspace is not aligned from the beginning.

**Comment by yhmtsai** [comment]
By the way, do you have the test such that we face the issue in our pipeline?

File: reference/test/solver/batch_bicgstab_kernels.cpp [hunk 19]
```diff
@@ -229,7 +229,7 @@ TYPED_TEST(BatchBicgstab, CanSolveEllSystem)
             .with_tolerance_type(gko::batch::stop::tolerance_type::relative)
             .on(this->exec);
     const int num_rows = 13;
-    const size_t num_batch_items = 2;
+    const size_t num_batch_items = 1;
```
[the remark this answers is not in the document]
Comment (pratikvn) [reply reference/test/solver/batch_bicgstab_kernels.cpp:232]: Yes, with num_batch_items=1 and without this fix, current develop gives the error

File: include/ginkgo/core/log/batch_logger.hpp (hunk 17 above)
Comment (pratikvn) [reply include/ginkgo/core/log/batch_logger.hpp:64]: I havent tested that, but it is possible, but for cases when we need to have different types, it would not help. This approach is more general.

**Comment by MarcelKoch** [comment]
> the check-format will fail because it uses develop instead of the updated precommit file

This is always so annoying....

**Review by MarcelKoch — APPROVED** [review]

File: reference/test/solver/batch_bicgstab_kernels.cpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (yhmtsai) [reply reference/test/solver/batch_bicgstab_kernels.cpp:232]: wait, I thought the error is from cuda not from reference. did the error also happen in reference?

File: include/ginkgo/core/log/batch_logger.hpp (hunk 17 above)
Comment (yhmtsai) [reply include/ginkgo/core/log/batch_logger.hpp:64]: one `if-else` condition should solve all cases

File: reference/test/solver/batch_bicgstab_kernels.cpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (pratikvn) [reply reference/test/solver/batch_bicgstab_kernels.cpp:232]: Yes, you are right. I somehow pushed it in the wrong file. It only fails in cuda and not reference.

File: include/ginkgo/core/log/batch_logger.hpp (hunk 17 above)
Comment (pratikvn) [reply include/ginkgo/core/log/batch_logger.hpp:64]: The plan would be to use this in all cases, for shared memory inside the kernels as well, so IMO CUB solution is a better and more general approach.

File: core/base/workspace_aliases.hpp [hunk 20]
```diff
@@ -0,0 +1,274 @@
...
+
+
+namespace gko {
+namespace detail {
+
+
+template <int num_allocs, int align_bytes = 8>
+GKO_ATTRIBUTES GKO_INLINE GKO_DEVICE_ERROR_TYPE create_workspace_aliases(
+    void* workspace_ptr, size_t& num_bytes, void* (&allocations)[num_allocs],
+    size_t (&allocation_sizes)[num_allocs])
```
Comment (yhmtsai) [inline core/base/workspace_aliases.hpp:45]:
```suggestion
    void* workspace_ptr, size_t& num_bytes, void* (&allocations)[num_allocs],
    const size_t (&allocation_sizes)[num_allocs])
```
just ensure it will not be changed accendentally.

File: core/log/batch_logger.cpp (hunk 18 above)
Comment (yhmtsai) [reply core/log/batch_logger.cpp:42]: okay, I may misunderstand the `reqd_workspace_size` meaning. I thought it is required workspace size. That's why I thought it will be failed when it is not aligned. The actual size is larger than required size == workspace size
However, it is just the size of workspace pointer in `create_workspace_aliases`.
It will be required workspace size (by function) when the aliases phase is failed.

Comment (yhmtsai) [inline core/log/batch_logger.cpp:42]:
```suggestion
    // it should at least `num * (sizeof(real_type) + sizeof(int))` with some additional buffer for alias purpose, but we simply request large enough size here.
    const size_type reqd_workspace_size = num_batch_items * 32;
```

File: include/ginkgo/core/solver/batch_solver_base.hpp (hunk 12 above)
Comment (yhmtsai) [reply include/ginkgo/core/solver/batch_solver_base.hpp:293]: maybe replaced it by log_data->get_workspace_size(num_batch)? It may help understanding for the future. 
At least, some comments here to indicate what this workspace for.

**Review by yhmtsai — APPROVED** [review]
LGTM. the name reqd_workspace_size is still confusing to me.
because it has different meaning in function input/output, I do not have idea about the better name

File: core/base/workspace_aliases.hpp [hunk 21]
```diff
@@ -0,0 +1,279 @@
...
+    /**
+     * @brief Returns an array of type @p T and length @p num_elems
+     */
+    template <typename T>
+    GKO_ATTRIBUTES alias<T> create_alias(std::size_t num_elems = 0);
+
+private:
+    GKO_ATTRIBUTES void set_bytes_required(std::size_t new_size)
+    {
+        size_ = max(size_, new_size);
```
Comment (MarcelKoch) [inline core/base/workspace_aliases.hpp:120]: this causes an error in our no-circular-deps test, because nothing provides the `max` function. I think it should be fine to use `std::max`. It should even be available in device code, since it's `constexpr` since c++14. If that is somehow not the case, then removing the `GKO_ATTRIBUTES` should be fine, since this functionality is not used in device codes anyway.
