### PR TITLE
Fix compiler error with nvhpc+mpi

### LINKED ISSUE #1638: Ginkgo v1.8.0: test/mpi/matrix.cpp", line 220: error: too many initializer values
I want to compile v1.8.0 with nvc++ from nvida_hpc_sdk 23.9.
When compiling:
[ 74%] Building CXX object test/mpi/CMakeFiles/test_mpi_matrix_omp.dir/matrix.cpp.o    
the following errors are thrown:
/test/mpi/matrix.cpp", line 220: error: too many initializer values                                                                                                                
          {{size_local[0], {{0, 0, 2}}},       

line 221: error: too many initializer values
           {size_local[1], {{0, 1, 5}}},

### PR DESCRIPTION
**Pull request by MarcelKoch**
This PR fixes a compiler error from nvhpc, when compiling a mpi test.

Fixes #1638

### CODE REVIEW

File: test/mpi/matrix.cpp [hunk 1]
```diff
@@ -207,25 +207,25 @@ TYPED_TEST(MatrixCreation, BuildFromExistingData)
...
     std::array<gko::dim<2>, 3> size_local{{{2, 2}, {2, 2}, {1, 1}}};
     std::array<matrix_data, 3> dist_input_local{
-        {{size_local[0], {{0, 0, 2}}},
-         {size_local[1], {{0, 1, 5}}},
-         {size_local[2],
-          std::initializer_list<
-              gko::detail::input_triple<value_type, local_index_type>>{}}}};
+        {{size_local[0], I<input_triple>{{0, 0, 2}}},
+         {size_local[1], I<input_triple>{{0, 1, 5}}},
+         {size_local[2]}}};
```
Comment (yhmtsai) [inline test/mpi/matrix.cpp:221]:
```suggestion
         {size_local[2], I<input_triple>{}}}};
```
does it work?

Comment (MarcelKoch) [reply test/mpi/matrix.cpp:221]: Yes, `matrix_data` has a constructor just with a size. In that case it has no non-zeros.

**Review by upsj — APPROVED** [review]
LGTM! Thanks for fixing this, I remember coming across it a while back, but I didn't remember to fix it then.

**Review by yhmtsai — APPROVED** [review]
